// Code generated by ent, DO NOT EDIT.

package venue

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the venue type in the database.
	Label = "venue"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldGooglePlaceID holds the string denoting the google_place_id field in the database.
	FieldGooglePlaceID = "google_place_id"
	// FieldFieldType holds the string denoting the field_type field in the database.
	FieldFieldType = "field_type"
	// FieldSurfaceType holds the string denoting the surface_type field in the database.
	FieldSurfaceType = "surface_type"
	// FieldCapacity holds the string denoting the capacity field in the database.
	FieldCapacity = "capacity"
	// FieldHourlyRate holds the string denoting the hourly_rate field in the database.
	FieldHourlyRate = "hourly_rate"
	// FieldFacilities holds the string denoting the facilities field in the database.
	FieldFacilities = "facilities"
	// FieldImages holds the string denoting the images field in the database.
	FieldImages = "images"
	// FieldContactInfo holds the string denoting the contact_info field in the database.
	FieldContactInfo = "contact_info"
	// FieldOperatingHours holds the string denoting the operating_hours field in the database.
	FieldOperatingHours = "operating_hours"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldIsVerified holds the string denoting the is_verified field in the database.
	FieldIsVerified = "is_verified"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldTotalRatings holds the string denoting the total_ratings field in the database.
	FieldTotalRatings = "total_ratings"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeMatches holds the string denoting the matches edge name in mutations.
	EdgeMatches = "matches"
	// Table holds the table name of the venue in the database.
	Table = "venues"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "venues"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// MatchesTable is the table that holds the matches relation/edge.
	MatchesTable = "matches"
	// MatchesInverseTable is the table name for the Match entity.
	// It exists in this package in order to avoid circular dependency with the "match" package.
	MatchesInverseTable = "matches"
	// MatchesColumn is the table column denoting the matches relation/edge.
	MatchesColumn = "venue_matches"
)

// Columns holds all SQL columns for venue fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAddress,
	FieldLatitude,
	FieldLongitude,
	FieldGooglePlaceID,
	FieldFieldType,
	FieldSurfaceType,
	FieldCapacity,
	FieldHourlyRate,
	FieldFacilities,
	FieldImages,
	FieldContactInfo,
	FieldOperatingHours,
	FieldOwnerID,
	FieldIsVerified,
	FieldIsActive,
	FieldRating,
	FieldTotalRatings,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "venues"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_owned_venues",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// GooglePlaceIDValidator is a validator for the "google_place_id" field. It is called by the builders before save.
	GooglePlaceIDValidator func(string) error
	// DefaultCapacity holds the default value on creation for the "capacity" field.
	DefaultCapacity int
	// CapacityValidator is a validator for the "capacity" field. It is called by the builders before save.
	CapacityValidator func(int) error
	// DefaultIsVerified holds the default value on creation for the "is_verified" field.
	DefaultIsVerified bool
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultRating holds the default value on creation for the "rating" field.
	DefaultRating float64
	// RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	RatingValidator func(float64) error
	// DefaultTotalRatings holds the default value on creation for the "total_ratings" field.
	DefaultTotalRatings int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// FieldType defines the type for the "field_type" enum field.
type FieldType string

// FieldType values.
const (
	FieldTypeFutsal   FieldType = "futsal"
	FieldTypeFootball FieldType = "football"
	FieldTypeAstro    FieldType = "astro"
)

func (ft FieldType) String() string {
	return string(ft)
}

// FieldTypeValidator is a validator for the "field_type" field enum values. It is called by the builders before save.
func FieldTypeValidator(ft FieldType) error {
	switch ft {
	case FieldTypeFutsal, FieldTypeFootball, FieldTypeAstro:
		return nil
	default:
		return fmt.Errorf("venue: invalid enum value for field_type field: %q", ft)
	}
}

// SurfaceType defines the type for the "surface_type" enum field.
type SurfaceType string

// SurfaceType values.
const (
	SurfaceTypeGrass      SurfaceType = "grass"
	SurfaceTypeArtificial SurfaceType = "artificial"
	SurfaceTypeConcrete   SurfaceType = "concrete"
)

func (st SurfaceType) String() string {
	return string(st)
}

// SurfaceTypeValidator is a validator for the "surface_type" field enum values. It is called by the builders before save.
func SurfaceTypeValidator(st SurfaceType) error {
	switch st {
	case SurfaceTypeGrass, SurfaceTypeArtificial, SurfaceTypeConcrete:
		return nil
	default:
		return fmt.Errorf("venue: invalid enum value for surface_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the Venue queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByLatitude orders the results by the latitude field.
func ByLatitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatitude, opts...).ToFunc()
}

// ByLongitude orders the results by the longitude field.
func ByLongitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongitude, opts...).ToFunc()
}

// ByGooglePlaceID orders the results by the google_place_id field.
func ByGooglePlaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGooglePlaceID, opts...).ToFunc()
}

// ByFieldType orders the results by the field_type field.
func ByFieldType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFieldType, opts...).ToFunc()
}

// BySurfaceType orders the results by the surface_type field.
func BySurfaceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSurfaceType, opts...).ToFunc()
}

// ByCapacity orders the results by the capacity field.
func ByCapacity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapacity, opts...).ToFunc()
}

// ByHourlyRate orders the results by the hourly_rate field.
func ByHourlyRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHourlyRate, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByIsVerified orders the results by the is_verified field.
func ByIsVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsVerified, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByTotalRatings orders the results by the total_ratings field.
func ByTotalRatings(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRatings, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByMatchesCount orders the results by matches count.
func ByMatchesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMatchesStep(), opts...)
	}
}

// ByMatches orders the results by matches terms.
func ByMatches(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMatchesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, OwnerTable, OwnerColumn),
	)
}
func newMatchesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MatchesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MatchesTable, MatchesColumn),
	)
}
