// Code generated by ent, DO NOT EDIT.

package venue

import (
	"kicknroar/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldName, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldAddress, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldLongitude, v))
}

// GooglePlaceID applies equality check predicate on the "google_place_id" field. It's identical to GooglePlaceIDEQ.
func GooglePlaceID(v string) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldGooglePlaceID, v))
}

// Capacity applies equality check predicate on the "capacity" field. It's identical to CapacityEQ.
func Capacity(v int) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldCapacity, v))
}

// HourlyRate applies equality check predicate on the "hourly_rate" field. It's identical to HourlyRateEQ.
func HourlyRate(v int) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldHourlyRate, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldOwnerID, v))
}

// IsVerified applies equality check predicate on the "is_verified" field. It's identical to IsVerifiedEQ.
func IsVerified(v bool) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldIsVerified, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldIsActive, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldRating, v))
}

// TotalRatings applies equality check predicate on the "total_ratings" field. It's identical to TotalRatingsEQ.
func TotalRatings(v int) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldTotalRatings, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Venue {
	return predicate.Venue(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Venue {
	return predicate.Venue(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Venue {
	return predicate.Venue(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Venue {
	return predicate.Venue(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Venue {
	return predicate.Venue(sql.FieldContainsFold(FieldName, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Venue {
	return predicate.Venue(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Venue {
	return predicate.Venue(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Venue {
	return predicate.Venue(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Venue {
	return predicate.Venue(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Venue {
	return predicate.Venue(sql.FieldContainsFold(FieldAddress, v))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldLatitude, v))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldLongitude, v))
}

// GooglePlaceIDEQ applies the EQ predicate on the "google_place_id" field.
func GooglePlaceIDEQ(v string) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldGooglePlaceID, v))
}

// GooglePlaceIDNEQ applies the NEQ predicate on the "google_place_id" field.
func GooglePlaceIDNEQ(v string) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldGooglePlaceID, v))
}

// GooglePlaceIDIn applies the In predicate on the "google_place_id" field.
func GooglePlaceIDIn(vs ...string) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldGooglePlaceID, vs...))
}

// GooglePlaceIDNotIn applies the NotIn predicate on the "google_place_id" field.
func GooglePlaceIDNotIn(vs ...string) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldGooglePlaceID, vs...))
}

// GooglePlaceIDGT applies the GT predicate on the "google_place_id" field.
func GooglePlaceIDGT(v string) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldGooglePlaceID, v))
}

// GooglePlaceIDGTE applies the GTE predicate on the "google_place_id" field.
func GooglePlaceIDGTE(v string) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldGooglePlaceID, v))
}

// GooglePlaceIDLT applies the LT predicate on the "google_place_id" field.
func GooglePlaceIDLT(v string) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldGooglePlaceID, v))
}

// GooglePlaceIDLTE applies the LTE predicate on the "google_place_id" field.
func GooglePlaceIDLTE(v string) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldGooglePlaceID, v))
}

// GooglePlaceIDContains applies the Contains predicate on the "google_place_id" field.
func GooglePlaceIDContains(v string) predicate.Venue {
	return predicate.Venue(sql.FieldContains(FieldGooglePlaceID, v))
}

// GooglePlaceIDHasPrefix applies the HasPrefix predicate on the "google_place_id" field.
func GooglePlaceIDHasPrefix(v string) predicate.Venue {
	return predicate.Venue(sql.FieldHasPrefix(FieldGooglePlaceID, v))
}

// GooglePlaceIDHasSuffix applies the HasSuffix predicate on the "google_place_id" field.
func GooglePlaceIDHasSuffix(v string) predicate.Venue {
	return predicate.Venue(sql.FieldHasSuffix(FieldGooglePlaceID, v))
}

// GooglePlaceIDIsNil applies the IsNil predicate on the "google_place_id" field.
func GooglePlaceIDIsNil() predicate.Venue {
	return predicate.Venue(sql.FieldIsNull(FieldGooglePlaceID))
}

// GooglePlaceIDNotNil applies the NotNil predicate on the "google_place_id" field.
func GooglePlaceIDNotNil() predicate.Venue {
	return predicate.Venue(sql.FieldNotNull(FieldGooglePlaceID))
}

// GooglePlaceIDEqualFold applies the EqualFold predicate on the "google_place_id" field.
func GooglePlaceIDEqualFold(v string) predicate.Venue {
	return predicate.Venue(sql.FieldEqualFold(FieldGooglePlaceID, v))
}

// GooglePlaceIDContainsFold applies the ContainsFold predicate on the "google_place_id" field.
func GooglePlaceIDContainsFold(v string) predicate.Venue {
	return predicate.Venue(sql.FieldContainsFold(FieldGooglePlaceID, v))
}

// FieldTypeEQ applies the EQ predicate on the "field_type" field.
func FieldTypeEQ(v FieldType) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldFieldType, v))
}

// FieldTypeNEQ applies the NEQ predicate on the "field_type" field.
func FieldTypeNEQ(v FieldType) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldFieldType, v))
}

// FieldTypeIn applies the In predicate on the "field_type" field.
func FieldTypeIn(vs ...FieldType) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldFieldType, vs...))
}

// FieldTypeNotIn applies the NotIn predicate on the "field_type" field.
func FieldTypeNotIn(vs ...FieldType) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldFieldType, vs...))
}

// SurfaceTypeEQ applies the EQ predicate on the "surface_type" field.
func SurfaceTypeEQ(v SurfaceType) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldSurfaceType, v))
}

// SurfaceTypeNEQ applies the NEQ predicate on the "surface_type" field.
func SurfaceTypeNEQ(v SurfaceType) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldSurfaceType, v))
}

// SurfaceTypeIn applies the In predicate on the "surface_type" field.
func SurfaceTypeIn(vs ...SurfaceType) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldSurfaceType, vs...))
}

// SurfaceTypeNotIn applies the NotIn predicate on the "surface_type" field.
func SurfaceTypeNotIn(vs ...SurfaceType) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldSurfaceType, vs...))
}

// SurfaceTypeIsNil applies the IsNil predicate on the "surface_type" field.
func SurfaceTypeIsNil() predicate.Venue {
	return predicate.Venue(sql.FieldIsNull(FieldSurfaceType))
}

// SurfaceTypeNotNil applies the NotNil predicate on the "surface_type" field.
func SurfaceTypeNotNil() predicate.Venue {
	return predicate.Venue(sql.FieldNotNull(FieldSurfaceType))
}

// CapacityEQ applies the EQ predicate on the "capacity" field.
func CapacityEQ(v int) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldCapacity, v))
}

// CapacityNEQ applies the NEQ predicate on the "capacity" field.
func CapacityNEQ(v int) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldCapacity, v))
}

// CapacityIn applies the In predicate on the "capacity" field.
func CapacityIn(vs ...int) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldCapacity, vs...))
}

// CapacityNotIn applies the NotIn predicate on the "capacity" field.
func CapacityNotIn(vs ...int) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldCapacity, vs...))
}

// CapacityGT applies the GT predicate on the "capacity" field.
func CapacityGT(v int) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldCapacity, v))
}

// CapacityGTE applies the GTE predicate on the "capacity" field.
func CapacityGTE(v int) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldCapacity, v))
}

// CapacityLT applies the LT predicate on the "capacity" field.
func CapacityLT(v int) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldCapacity, v))
}

// CapacityLTE applies the LTE predicate on the "capacity" field.
func CapacityLTE(v int) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldCapacity, v))
}

// HourlyRateEQ applies the EQ predicate on the "hourly_rate" field.
func HourlyRateEQ(v int) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldHourlyRate, v))
}

// HourlyRateNEQ applies the NEQ predicate on the "hourly_rate" field.
func HourlyRateNEQ(v int) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldHourlyRate, v))
}

// HourlyRateIn applies the In predicate on the "hourly_rate" field.
func HourlyRateIn(vs ...int) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldHourlyRate, vs...))
}

// HourlyRateNotIn applies the NotIn predicate on the "hourly_rate" field.
func HourlyRateNotIn(vs ...int) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldHourlyRate, vs...))
}

// HourlyRateGT applies the GT predicate on the "hourly_rate" field.
func HourlyRateGT(v int) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldHourlyRate, v))
}

// HourlyRateGTE applies the GTE predicate on the "hourly_rate" field.
func HourlyRateGTE(v int) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldHourlyRate, v))
}

// HourlyRateLT applies the LT predicate on the "hourly_rate" field.
func HourlyRateLT(v int) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldHourlyRate, v))
}

// HourlyRateLTE applies the LTE predicate on the "hourly_rate" field.
func HourlyRateLTE(v int) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldHourlyRate, v))
}

// HourlyRateIsNil applies the IsNil predicate on the "hourly_rate" field.
func HourlyRateIsNil() predicate.Venue {
	return predicate.Venue(sql.FieldIsNull(FieldHourlyRate))
}

// HourlyRateNotNil applies the NotNil predicate on the "hourly_rate" field.
func HourlyRateNotNil() predicate.Venue {
	return predicate.Venue(sql.FieldNotNull(FieldHourlyRate))
}

// FacilitiesIsNil applies the IsNil predicate on the "facilities" field.
func FacilitiesIsNil() predicate.Venue {
	return predicate.Venue(sql.FieldIsNull(FieldFacilities))
}

// FacilitiesNotNil applies the NotNil predicate on the "facilities" field.
func FacilitiesNotNil() predicate.Venue {
	return predicate.Venue(sql.FieldNotNull(FieldFacilities))
}

// ImagesIsNil applies the IsNil predicate on the "images" field.
func ImagesIsNil() predicate.Venue {
	return predicate.Venue(sql.FieldIsNull(FieldImages))
}

// ImagesNotNil applies the NotNil predicate on the "images" field.
func ImagesNotNil() predicate.Venue {
	return predicate.Venue(sql.FieldNotNull(FieldImages))
}

// ContactInfoIsNil applies the IsNil predicate on the "contact_info" field.
func ContactInfoIsNil() predicate.Venue {
	return predicate.Venue(sql.FieldIsNull(FieldContactInfo))
}

// ContactInfoNotNil applies the NotNil predicate on the "contact_info" field.
func ContactInfoNotNil() predicate.Venue {
	return predicate.Venue(sql.FieldNotNull(FieldContactInfo))
}

// OperatingHoursIsNil applies the IsNil predicate on the "operating_hours" field.
func OperatingHoursIsNil() predicate.Venue {
	return predicate.Venue(sql.FieldIsNull(FieldOperatingHours))
}

// OperatingHoursNotNil applies the NotNil predicate on the "operating_hours" field.
func OperatingHoursNotNil() predicate.Venue {
	return predicate.Venue(sql.FieldNotNull(FieldOperatingHours))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uuid.UUID) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDIsNil applies the IsNil predicate on the "owner_id" field.
func OwnerIDIsNil() predicate.Venue {
	return predicate.Venue(sql.FieldIsNull(FieldOwnerID))
}

// OwnerIDNotNil applies the NotNil predicate on the "owner_id" field.
func OwnerIDNotNil() predicate.Venue {
	return predicate.Venue(sql.FieldNotNull(FieldOwnerID))
}

// IsVerifiedEQ applies the EQ predicate on the "is_verified" field.
func IsVerifiedEQ(v bool) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldIsVerified, v))
}

// IsVerifiedNEQ applies the NEQ predicate on the "is_verified" field.
func IsVerifiedNEQ(v bool) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldIsVerified, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldIsActive, v))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...float64) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...float64) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v float64) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldRating, v))
}

// TotalRatingsEQ applies the EQ predicate on the "total_ratings" field.
func TotalRatingsEQ(v int) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldTotalRatings, v))
}

// TotalRatingsNEQ applies the NEQ predicate on the "total_ratings" field.
func TotalRatingsNEQ(v int) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldTotalRatings, v))
}

// TotalRatingsIn applies the In predicate on the "total_ratings" field.
func TotalRatingsIn(vs ...int) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldTotalRatings, vs...))
}

// TotalRatingsNotIn applies the NotIn predicate on the "total_ratings" field.
func TotalRatingsNotIn(vs ...int) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldTotalRatings, vs...))
}

// TotalRatingsGT applies the GT predicate on the "total_ratings" field.
func TotalRatingsGT(v int) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldTotalRatings, v))
}

// TotalRatingsGTE applies the GTE predicate on the "total_ratings" field.
func TotalRatingsGTE(v int) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldTotalRatings, v))
}

// TotalRatingsLT applies the LT predicate on the "total_ratings" field.
func TotalRatingsLT(v int) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldTotalRatings, v))
}

// TotalRatingsLTE applies the LTE predicate on the "total_ratings" field.
func TotalRatingsLTE(v int) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldTotalRatings, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Venue {
	return predicate.Venue(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Venue {
	return predicate.Venue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Venue {
	return predicate.Venue(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMatches applies the HasEdge predicate on the "matches" edge.
func HasMatches() predicate.Venue {
	return predicate.Venue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MatchesTable, MatchesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMatchesWith applies the HasEdge predicate on the "matches" edge with a given conditions (other predicates).
func HasMatchesWith(preds ...predicate.Match) predicate.Venue {
	return predicate.Venue(func(s *sql.Selector) {
		step := newMatchesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Venue) predicate.Venue {
	return predicate.Venue(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Venue) predicate.Venue {
	return predicate.Venue(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Venue) predicate.Venue {
	return predicate.Venue(sql.NotPredicates(p))
}
