// Code generated by ent, DO NOT EDIT.

package match

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the match type in the database.
	Label = "match"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatorID holds the string denoting the creator_id field in the database.
	FieldCreatorID = "creator_id"
	// FieldVenueID holds the string denoting the venue_id field in the database.
	FieldVenueID = "venue_id"
	// FieldMatchDate holds the string denoting the match_date field in the database.
	FieldMatchDate = "match_date"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldDurationHours holds the string denoting the duration_hours field in the database.
	FieldDurationHours = "duration_hours"
	// FieldMaxPlayers holds the string denoting the max_players field in the database.
	FieldMaxPlayers = "max_players"
	// FieldCurrentPlayers holds the string denoting the current_players field in the database.
	FieldCurrentPlayers = "current_players"
	// FieldCostPerPlayer holds the string denoting the cost_per_player field in the database.
	FieldCostPerPlayer = "cost_per_player"
	// FieldSkillLevelRequired holds the string denoting the skill_level_required field in the database.
	FieldSkillLevelRequired = "skill_level_required"
	// FieldMatchType holds the string denoting the match_type field in the database.
	FieldMatchType = "match_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVisibility holds the string denoting the visibility field in the database.
	FieldVisibility = "visibility"
	// FieldRulesNotes holds the string denoting the rules_notes field in the database.
	FieldRulesNotes = "rules_notes"
	// FieldReminderSent holds the string denoting the reminder_sent field in the database.
	FieldReminderSent = "reminder_sent"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeVenue holds the string denoting the venue edge name in mutations.
	EdgeVenue = "venue"
	// EdgeParticipants holds the string denoting the participants edge name in mutations.
	EdgeParticipants = "participants"
	// EdgeNotifications holds the string denoting the notifications edge name in mutations.
	EdgeNotifications = "notifications"
	// Table holds the table name of the match in the database.
	Table = "matches"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "matches"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "creator_id"
	// VenueTable is the table that holds the venue relation/edge.
	VenueTable = "matches"
	// VenueInverseTable is the table name for the Venue entity.
	// It exists in this package in order to avoid circular dependency with the "venue" package.
	VenueInverseTable = "venues"
	// VenueColumn is the table column denoting the venue relation/edge.
	VenueColumn = "venue_id"
	// ParticipantsTable is the table that holds the participants relation/edge.
	ParticipantsTable = "match_participants"
	// ParticipantsInverseTable is the table name for the MatchParticipant entity.
	// It exists in this package in order to avoid circular dependency with the "matchparticipant" package.
	ParticipantsInverseTable = "match_participants"
	// ParticipantsColumn is the table column denoting the participants relation/edge.
	ParticipantsColumn = "match_participants"
	// NotificationsTable is the table that holds the notifications relation/edge.
	NotificationsTable = "notifications"
	// NotificationsInverseTable is the table name for the Notification entity.
	// It exists in this package in order to avoid circular dependency with the "notification" package.
	NotificationsInverseTable = "notifications"
	// NotificationsColumn is the table column denoting the notifications relation/edge.
	NotificationsColumn = "match_notifications"
)

// Columns holds all SQL columns for match fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldCreatorID,
	FieldVenueID,
	FieldMatchDate,
	FieldStartTime,
	FieldDurationHours,
	FieldMaxPlayers,
	FieldCurrentPlayers,
	FieldCostPerPlayer,
	FieldSkillLevelRequired,
	FieldMatchType,
	FieldStatus,
	FieldVisibility,
	FieldRulesNotes,
	FieldReminderSent,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "matches"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_created_matches",
	"venue_matches",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultDurationHours holds the default value on creation for the "duration_hours" field.
	DefaultDurationHours float64
	// DefaultMaxPlayers holds the default value on creation for the "max_players" field.
	DefaultMaxPlayers int
	// MaxPlayersValidator is a validator for the "max_players" field. It is called by the builders before save.
	MaxPlayersValidator func(int) error
	// DefaultCurrentPlayers holds the default value on creation for the "current_players" field.
	DefaultCurrentPlayers int
	// CurrentPlayersValidator is a validator for the "current_players" field. It is called by the builders before save.
	CurrentPlayersValidator func(int) error
	// CostPerPlayerValidator is a validator for the "cost_per_player" field. It is called by the builders before save.
	CostPerPlayerValidator func(int) error
	// DefaultReminderSent holds the default value on creation for the "reminder_sent" field.
	DefaultReminderSent bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// SkillLevelRequired defines the type for the "skill_level_required" enum field.
type SkillLevelRequired string

// SkillLevelRequired values.
const (
	SkillLevelRequiredBeginner     SkillLevelRequired = "beginner"
	SkillLevelRequiredIntermediate SkillLevelRequired = "intermediate"
	SkillLevelRequiredAdvanced     SkillLevelRequired = "advanced"
	SkillLevelRequiredProfessional SkillLevelRequired = "professional"
)

func (slr SkillLevelRequired) String() string {
	return string(slr)
}

// SkillLevelRequiredValidator is a validator for the "skill_level_required" field enum values. It is called by the builders before save.
func SkillLevelRequiredValidator(slr SkillLevelRequired) error {
	switch slr {
	case SkillLevelRequiredBeginner, SkillLevelRequiredIntermediate, SkillLevelRequiredAdvanced, SkillLevelRequiredProfessional:
		return nil
	default:
		return fmt.Errorf("match: invalid enum value for skill_level_required field: %q", slr)
	}
}

// MatchType defines the type for the "match_type" enum field.
type MatchType string

// MatchTypeCasual is the default value of the MatchType enum.
const DefaultMatchType = MatchTypeCasual

// MatchType values.
const (
	MatchTypeCasual      MatchType = "casual"
	MatchTypeCompetitive MatchType = "competitive"
	MatchTypeTournament  MatchType = "tournament"
)

func (mt MatchType) String() string {
	return string(mt)
}

// MatchTypeValidator is a validator for the "match_type" field enum values. It is called by the builders before save.
func MatchTypeValidator(mt MatchType) error {
	switch mt {
	case MatchTypeCasual, MatchTypeCompetitive, MatchTypeTournament:
		return nil
	default:
		return fmt.Errorf("match: invalid enum value for match_type field: %q", mt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusOpen is the default value of the Status enum.
const DefaultStatus = StatusOpen

// Status values.
const (
	StatusOpen      Status = "open"
	StatusFull      Status = "full"
	StatusConfirmed Status = "confirmed"
	StatusOngoing   Status = "ongoing"
	StatusCompleted Status = "completed"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusOpen, StatusFull, StatusConfirmed, StatusOngoing, StatusCompleted, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("match: invalid enum value for status field: %q", s)
	}
}

// Visibility defines the type for the "visibility" enum field.
type Visibility string

// VisibilityPublic is the default value of the Visibility enum.
const DefaultVisibility = VisibilityPublic

// Visibility values.
const (
	VisibilityPublic      Visibility = "public"
	VisibilityPrivate     Visibility = "private"
	VisibilityFriendsOnly Visibility = "friends_only"
)

func (v Visibility) String() string {
	return string(v)
}

// VisibilityValidator is a validator for the "visibility" field enum values. It is called by the builders before save.
func VisibilityValidator(v Visibility) error {
	switch v {
	case VisibilityPublic, VisibilityPrivate, VisibilityFriendsOnly:
		return nil
	default:
		return fmt.Errorf("match: invalid enum value for visibility field: %q", v)
	}
}

// OrderOption defines the ordering options for the Match queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatorID orders the results by the creator_id field.
func ByCreatorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatorID, opts...).ToFunc()
}

// ByVenueID orders the results by the venue_id field.
func ByVenueID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVenueID, opts...).ToFunc()
}

// ByMatchDate orders the results by the match_date field.
func ByMatchDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchDate, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByDurationHours orders the results by the duration_hours field.
func ByDurationHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationHours, opts...).ToFunc()
}

// ByMaxPlayers orders the results by the max_players field.
func ByMaxPlayers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxPlayers, opts...).ToFunc()
}

// ByCurrentPlayers orders the results by the current_players field.
func ByCurrentPlayers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPlayers, opts...).ToFunc()
}

// ByCostPerPlayer orders the results by the cost_per_player field.
func ByCostPerPlayer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostPerPlayer, opts...).ToFunc()
}

// BySkillLevelRequired orders the results by the skill_level_required field.
func BySkillLevelRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillLevelRequired, opts...).ToFunc()
}

// ByMatchType orders the results by the match_type field.
func ByMatchType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVisibility orders the results by the visibility field.
func ByVisibility(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisibility, opts...).ToFunc()
}

// ByRulesNotes orders the results by the rules_notes field.
func ByRulesNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRulesNotes, opts...).ToFunc()
}

// ByReminderSent orders the results by the reminder_sent field.
func ByReminderSent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReminderSent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByVenueField orders the results by venue field.
func ByVenueField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVenueStep(), sql.OrderByField(field, opts...))
	}
}

// ByParticipantsCount orders the results by participants count.
func ByParticipantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newParticipantsStep(), opts...)
	}
}

// ByParticipants orders the results by participants terms.
func ByParticipants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParticipantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNotificationsCount orders the results by notifications count.
func ByNotificationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationsStep(), opts...)
	}
}

// ByNotifications orders the results by notifications terms.
func ByNotifications(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CreatorTable, CreatorColumn),
	)
}
func newVenueStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VenueInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, VenueTable, VenueColumn),
	)
}
func newParticipantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParticipantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ParticipantsTable, ParticipantsColumn),
	)
}
func newNotificationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
	)
}
