// Code generated by ent, DO NOT EDIT.

package match

import (
	"kicknroar/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldDescription, v))
}

// CreatorID applies equality check predicate on the "creator_id" field. It's identical to CreatorIDEQ.
func CreatorID(v uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldCreatorID, v))
}

// VenueID applies equality check predicate on the "venue_id" field. It's identical to VenueIDEQ.
func VenueID(v uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldVenueID, v))
}

// MatchDate applies equality check predicate on the "match_date" field. It's identical to MatchDateEQ.
func MatchDate(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldMatchDate, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldStartTime, v))
}

// DurationHours applies equality check predicate on the "duration_hours" field. It's identical to DurationHoursEQ.
func DurationHours(v float64) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldDurationHours, v))
}

// MaxPlayers applies equality check predicate on the "max_players" field. It's identical to MaxPlayersEQ.
func MaxPlayers(v int) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldMaxPlayers, v))
}

// CurrentPlayers applies equality check predicate on the "current_players" field. It's identical to CurrentPlayersEQ.
func CurrentPlayers(v int) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldCurrentPlayers, v))
}

// CostPerPlayer applies equality check predicate on the "cost_per_player" field. It's identical to CostPerPlayerEQ.
func CostPerPlayer(v int) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldCostPerPlayer, v))
}

// RulesNotes applies equality check predicate on the "rules_notes" field. It's identical to RulesNotesEQ.
func RulesNotes(v string) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldRulesNotes, v))
}

// ReminderSent applies equality check predicate on the "reminder_sent" field. It's identical to ReminderSentEQ.
func ReminderSent(v bool) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldReminderSent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Match {
	return predicate.Match(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Match {
	return predicate.Match(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Match {
	return predicate.Match(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Match {
	return predicate.Match(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Match {
	return predicate.Match(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Match {
	return predicate.Match(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Match {
	return predicate.Match(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Match {
	return predicate.Match(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Match {
	return predicate.Match(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Match {
	return predicate.Match(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Match {
	return predicate.Match(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Match {
	return predicate.Match(sql.FieldContainsFold(FieldDescription, v))
}

// CreatorIDEQ applies the EQ predicate on the "creator_id" field.
func CreatorIDEQ(v uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldCreatorID, v))
}

// CreatorIDNEQ applies the NEQ predicate on the "creator_id" field.
func CreatorIDNEQ(v uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldCreatorID, v))
}

// CreatorIDIn applies the In predicate on the "creator_id" field.
func CreatorIDIn(vs ...uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldCreatorID, vs...))
}

// CreatorIDNotIn applies the NotIn predicate on the "creator_id" field.
func CreatorIDNotIn(vs ...uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldCreatorID, vs...))
}

// VenueIDEQ applies the EQ predicate on the "venue_id" field.
func VenueIDEQ(v uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldVenueID, v))
}

// VenueIDNEQ applies the NEQ predicate on the "venue_id" field.
func VenueIDNEQ(v uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldVenueID, v))
}

// VenueIDIn applies the In predicate on the "venue_id" field.
func VenueIDIn(vs ...uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldVenueID, vs...))
}

// VenueIDNotIn applies the NotIn predicate on the "venue_id" field.
func VenueIDNotIn(vs ...uuid.UUID) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldVenueID, vs...))
}

// MatchDateEQ applies the EQ predicate on the "match_date" field.
func MatchDateEQ(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldMatchDate, v))
}

// MatchDateNEQ applies the NEQ predicate on the "match_date" field.
func MatchDateNEQ(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldMatchDate, v))
}

// MatchDateIn applies the In predicate on the "match_date" field.
func MatchDateIn(vs ...time.Time) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldMatchDate, vs...))
}

// MatchDateNotIn applies the NotIn predicate on the "match_date" field.
func MatchDateNotIn(vs ...time.Time) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldMatchDate, vs...))
}

// MatchDateGT applies the GT predicate on the "match_date" field.
func MatchDateGT(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldMatchDate, v))
}

// MatchDateGTE applies the GTE predicate on the "match_date" field.
func MatchDateGTE(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldMatchDate, v))
}

// MatchDateLT applies the LT predicate on the "match_date" field.
func MatchDateLT(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldMatchDate, v))
}

// MatchDateLTE applies the LTE predicate on the "match_date" field.
func MatchDateLTE(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldMatchDate, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldStartTime, v))
}

// DurationHoursEQ applies the EQ predicate on the "duration_hours" field.
func DurationHoursEQ(v float64) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldDurationHours, v))
}

// DurationHoursNEQ applies the NEQ predicate on the "duration_hours" field.
func DurationHoursNEQ(v float64) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldDurationHours, v))
}

// DurationHoursIn applies the In predicate on the "duration_hours" field.
func DurationHoursIn(vs ...float64) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldDurationHours, vs...))
}

// DurationHoursNotIn applies the NotIn predicate on the "duration_hours" field.
func DurationHoursNotIn(vs ...float64) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldDurationHours, vs...))
}

// DurationHoursGT applies the GT predicate on the "duration_hours" field.
func DurationHoursGT(v float64) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldDurationHours, v))
}

// DurationHoursGTE applies the GTE predicate on the "duration_hours" field.
func DurationHoursGTE(v float64) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldDurationHours, v))
}

// DurationHoursLT applies the LT predicate on the "duration_hours" field.
func DurationHoursLT(v float64) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldDurationHours, v))
}

// DurationHoursLTE applies the LTE predicate on the "duration_hours" field.
func DurationHoursLTE(v float64) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldDurationHours, v))
}

// MaxPlayersEQ applies the EQ predicate on the "max_players" field.
func MaxPlayersEQ(v int) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldMaxPlayers, v))
}

// MaxPlayersNEQ applies the NEQ predicate on the "max_players" field.
func MaxPlayersNEQ(v int) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldMaxPlayers, v))
}

// MaxPlayersIn applies the In predicate on the "max_players" field.
func MaxPlayersIn(vs ...int) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldMaxPlayers, vs...))
}

// MaxPlayersNotIn applies the NotIn predicate on the "max_players" field.
func MaxPlayersNotIn(vs ...int) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldMaxPlayers, vs...))
}

// MaxPlayersGT applies the GT predicate on the "max_players" field.
func MaxPlayersGT(v int) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldMaxPlayers, v))
}

// MaxPlayersGTE applies the GTE predicate on the "max_players" field.
func MaxPlayersGTE(v int) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldMaxPlayers, v))
}

// MaxPlayersLT applies the LT predicate on the "max_players" field.
func MaxPlayersLT(v int) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldMaxPlayers, v))
}

// MaxPlayersLTE applies the LTE predicate on the "max_players" field.
func MaxPlayersLTE(v int) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldMaxPlayers, v))
}

// CurrentPlayersEQ applies the EQ predicate on the "current_players" field.
func CurrentPlayersEQ(v int) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldCurrentPlayers, v))
}

// CurrentPlayersNEQ applies the NEQ predicate on the "current_players" field.
func CurrentPlayersNEQ(v int) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldCurrentPlayers, v))
}

// CurrentPlayersIn applies the In predicate on the "current_players" field.
func CurrentPlayersIn(vs ...int) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldCurrentPlayers, vs...))
}

// CurrentPlayersNotIn applies the NotIn predicate on the "current_players" field.
func CurrentPlayersNotIn(vs ...int) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldCurrentPlayers, vs...))
}

// CurrentPlayersGT applies the GT predicate on the "current_players" field.
func CurrentPlayersGT(v int) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldCurrentPlayers, v))
}

// CurrentPlayersGTE applies the GTE predicate on the "current_players" field.
func CurrentPlayersGTE(v int) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldCurrentPlayers, v))
}

// CurrentPlayersLT applies the LT predicate on the "current_players" field.
func CurrentPlayersLT(v int) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldCurrentPlayers, v))
}

// CurrentPlayersLTE applies the LTE predicate on the "current_players" field.
func CurrentPlayersLTE(v int) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldCurrentPlayers, v))
}

// CostPerPlayerEQ applies the EQ predicate on the "cost_per_player" field.
func CostPerPlayerEQ(v int) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldCostPerPlayer, v))
}

// CostPerPlayerNEQ applies the NEQ predicate on the "cost_per_player" field.
func CostPerPlayerNEQ(v int) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldCostPerPlayer, v))
}

// CostPerPlayerIn applies the In predicate on the "cost_per_player" field.
func CostPerPlayerIn(vs ...int) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldCostPerPlayer, vs...))
}

// CostPerPlayerNotIn applies the NotIn predicate on the "cost_per_player" field.
func CostPerPlayerNotIn(vs ...int) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldCostPerPlayer, vs...))
}

// CostPerPlayerGT applies the GT predicate on the "cost_per_player" field.
func CostPerPlayerGT(v int) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldCostPerPlayer, v))
}

// CostPerPlayerGTE applies the GTE predicate on the "cost_per_player" field.
func CostPerPlayerGTE(v int) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldCostPerPlayer, v))
}

// CostPerPlayerLT applies the LT predicate on the "cost_per_player" field.
func CostPerPlayerLT(v int) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldCostPerPlayer, v))
}

// CostPerPlayerLTE applies the LTE predicate on the "cost_per_player" field.
func CostPerPlayerLTE(v int) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldCostPerPlayer, v))
}

// SkillLevelRequiredEQ applies the EQ predicate on the "skill_level_required" field.
func SkillLevelRequiredEQ(v SkillLevelRequired) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldSkillLevelRequired, v))
}

// SkillLevelRequiredNEQ applies the NEQ predicate on the "skill_level_required" field.
func SkillLevelRequiredNEQ(v SkillLevelRequired) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldSkillLevelRequired, v))
}

// SkillLevelRequiredIn applies the In predicate on the "skill_level_required" field.
func SkillLevelRequiredIn(vs ...SkillLevelRequired) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldSkillLevelRequired, vs...))
}

// SkillLevelRequiredNotIn applies the NotIn predicate on the "skill_level_required" field.
func SkillLevelRequiredNotIn(vs ...SkillLevelRequired) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldSkillLevelRequired, vs...))
}

// SkillLevelRequiredIsNil applies the IsNil predicate on the "skill_level_required" field.
func SkillLevelRequiredIsNil() predicate.Match {
	return predicate.Match(sql.FieldIsNull(FieldSkillLevelRequired))
}

// SkillLevelRequiredNotNil applies the NotNil predicate on the "skill_level_required" field.
func SkillLevelRequiredNotNil() predicate.Match {
	return predicate.Match(sql.FieldNotNull(FieldSkillLevelRequired))
}

// MatchTypeEQ applies the EQ predicate on the "match_type" field.
func MatchTypeEQ(v MatchType) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldMatchType, v))
}

// MatchTypeNEQ applies the NEQ predicate on the "match_type" field.
func MatchTypeNEQ(v MatchType) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldMatchType, v))
}

// MatchTypeIn applies the In predicate on the "match_type" field.
func MatchTypeIn(vs ...MatchType) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldMatchType, vs...))
}

// MatchTypeNotIn applies the NotIn predicate on the "match_type" field.
func MatchTypeNotIn(vs ...MatchType) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldMatchType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldStatus, vs...))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v Visibility) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v Visibility) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...Visibility) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...Visibility) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldVisibility, vs...))
}

// RulesNotesEQ applies the EQ predicate on the "rules_notes" field.
func RulesNotesEQ(v string) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldRulesNotes, v))
}

// RulesNotesNEQ applies the NEQ predicate on the "rules_notes" field.
func RulesNotesNEQ(v string) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldRulesNotes, v))
}

// RulesNotesIn applies the In predicate on the "rules_notes" field.
func RulesNotesIn(vs ...string) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldRulesNotes, vs...))
}

// RulesNotesNotIn applies the NotIn predicate on the "rules_notes" field.
func RulesNotesNotIn(vs ...string) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldRulesNotes, vs...))
}

// RulesNotesGT applies the GT predicate on the "rules_notes" field.
func RulesNotesGT(v string) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldRulesNotes, v))
}

// RulesNotesGTE applies the GTE predicate on the "rules_notes" field.
func RulesNotesGTE(v string) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldRulesNotes, v))
}

// RulesNotesLT applies the LT predicate on the "rules_notes" field.
func RulesNotesLT(v string) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldRulesNotes, v))
}

// RulesNotesLTE applies the LTE predicate on the "rules_notes" field.
func RulesNotesLTE(v string) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldRulesNotes, v))
}

// RulesNotesContains applies the Contains predicate on the "rules_notes" field.
func RulesNotesContains(v string) predicate.Match {
	return predicate.Match(sql.FieldContains(FieldRulesNotes, v))
}

// RulesNotesHasPrefix applies the HasPrefix predicate on the "rules_notes" field.
func RulesNotesHasPrefix(v string) predicate.Match {
	return predicate.Match(sql.FieldHasPrefix(FieldRulesNotes, v))
}

// RulesNotesHasSuffix applies the HasSuffix predicate on the "rules_notes" field.
func RulesNotesHasSuffix(v string) predicate.Match {
	return predicate.Match(sql.FieldHasSuffix(FieldRulesNotes, v))
}

// RulesNotesIsNil applies the IsNil predicate on the "rules_notes" field.
func RulesNotesIsNil() predicate.Match {
	return predicate.Match(sql.FieldIsNull(FieldRulesNotes))
}

// RulesNotesNotNil applies the NotNil predicate on the "rules_notes" field.
func RulesNotesNotNil() predicate.Match {
	return predicate.Match(sql.FieldNotNull(FieldRulesNotes))
}

// RulesNotesEqualFold applies the EqualFold predicate on the "rules_notes" field.
func RulesNotesEqualFold(v string) predicate.Match {
	return predicate.Match(sql.FieldEqualFold(FieldRulesNotes, v))
}

// RulesNotesContainsFold applies the ContainsFold predicate on the "rules_notes" field.
func RulesNotesContainsFold(v string) predicate.Match {
	return predicate.Match(sql.FieldContainsFold(FieldRulesNotes, v))
}

// ReminderSentEQ applies the EQ predicate on the "reminder_sent" field.
func ReminderSentEQ(v bool) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldReminderSent, v))
}

// ReminderSentNEQ applies the NEQ predicate on the "reminder_sent" field.
func ReminderSentNEQ(v bool) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldReminderSent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Match {
	return predicate.Match(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Match {
	return predicate.Match(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Match {
	return predicate.Match(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.Match {
	return predicate.Match(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.Match {
	return predicate.Match(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVenue applies the HasEdge predicate on the "venue" edge.
func HasVenue() predicate.Match {
	return predicate.Match(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, VenueTable, VenueColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVenueWith applies the HasEdge predicate on the "venue" edge with a given conditions (other predicates).
func HasVenueWith(preds ...predicate.Venue) predicate.Match {
	return predicate.Match(func(s *sql.Selector) {
		step := newVenueStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParticipants applies the HasEdge predicate on the "participants" edge.
func HasParticipants() predicate.Match {
	return predicate.Match(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ParticipantsTable, ParticipantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParticipantsWith applies the HasEdge predicate on the "participants" edge with a given conditions (other predicates).
func HasParticipantsWith(preds ...predicate.MatchParticipant) predicate.Match {
	return predicate.Match(func(s *sql.Selector) {
		step := newParticipantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotifications applies the HasEdge predicate on the "notifications" edge.
func HasNotifications() predicate.Match {
	return predicate.Match(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationsWith applies the HasEdge predicate on the "notifications" edge with a given conditions (other predicates).
func HasNotificationsWith(preds ...predicate.Notification) predicate.Match {
	return predicate.Match(func(s *sql.Selector) {
		step := newNotificationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Match) predicate.Match {
	return predicate.Match(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Match) predicate.Match {
	return predicate.Match(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Match) predicate.Match {
	return predicate.Match(sql.NotPredicates(p))
}
