// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kicknroar/internal/ent/match"
	"kicknroar/internal/ent/user"
	"kicknroar/internal/ent/venue"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Match is the model entity for the Match schema.
type Match struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Match title
	Title string `json:"title,omitempty"`
	// Match description
	Description string `json:"description,omitempty"`
	// User who created the match
	CreatorID uuid.UUID `json:"creator_id,omitempty"`
	// Venue where match will be played
	VenueID uuid.UUID `json:"venue_id,omitempty"`
	// Date of the match
	MatchDate time.Time `json:"match_date,omitempty"`
	// Start time of the match
	StartTime time.Time `json:"start_time,omitempty"`
	// Duration in hours
	DurationHours float64 `json:"duration_hours,omitempty"`
	// Maximum number of players
	MaxPlayers int `json:"max_players,omitempty"`
	// Current number of players
	CurrentPlayers int `json:"current_players,omitempty"`
	// Cost per player in BDT
	CostPerPlayer int `json:"cost_per_player,omitempty"`
	// Required skill level
	SkillLevelRequired match.SkillLevelRequired `json:"skill_level_required,omitempty"`
	// Type of match
	MatchType match.MatchType `json:"match_type,omitempty"`
	// Match status
	Status match.Status `json:"status,omitempty"`
	// Match visibility
	Visibility match.Visibility `json:"visibility,omitempty"`
	// Rules and notes
	RulesNotes string `json:"rules_notes,omitempty"`
	// Whether reminder has been sent
	ReminderSent bool `json:"reminder_sent,omitempty"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MatchQuery when eager-loading is set.
	Edges                MatchEdges `json:"edges"`
	user_created_matches *uuid.UUID
	venue_matches        *uuid.UUID
	selectValues         sql.SelectValues
}

// MatchEdges holds the relations/edges for other nodes in the graph.
type MatchEdges struct {
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Venue holds the value of the venue edge.
	Venue *Venue `json:"venue,omitempty"`
	// Participants holds the value of the participants edge.
	Participants []*MatchParticipant `json:"participants,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*Notification `json:"notifications,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MatchEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// VenueOrErr returns the Venue value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MatchEdges) VenueOrErr() (*Venue, error) {
	if e.Venue != nil {
		return e.Venue, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: venue.Label}
	}
	return nil, &NotLoadedError{edge: "venue"}
}

// ParticipantsOrErr returns the Participants value or an error if the edge
// was not loaded in eager-loading.
func (e MatchEdges) ParticipantsOrErr() ([]*MatchParticipant, error) {
	if e.loadedTypes[2] {
		return e.Participants, nil
	}
	return nil, &NotLoadedError{edge: "participants"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e MatchEdges) NotificationsOrErr() ([]*Notification, error) {
	if e.loadedTypes[3] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Match) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case match.FieldReminderSent:
			values[i] = new(sql.NullBool)
		case match.FieldDurationHours:
			values[i] = new(sql.NullFloat64)
		case match.FieldMaxPlayers, match.FieldCurrentPlayers, match.FieldCostPerPlayer:
			values[i] = new(sql.NullInt64)
		case match.FieldTitle, match.FieldDescription, match.FieldSkillLevelRequired, match.FieldMatchType, match.FieldStatus, match.FieldVisibility, match.FieldRulesNotes:
			values[i] = new(sql.NullString)
		case match.FieldMatchDate, match.FieldStartTime, match.FieldCreatedAt, match.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case match.FieldID, match.FieldCreatorID, match.FieldVenueID:
			values[i] = new(uuid.UUID)
		case match.ForeignKeys[0]: // user_created_matches
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case match.ForeignKeys[1]: // venue_matches
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Match fields.
func (_m *Match) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case match.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case match.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case match.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case match.FieldCreatorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field creator_id", values[i])
			} else if value != nil {
				_m.CreatorID = *value
			}
		case match.FieldVenueID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field venue_id", values[i])
			} else if value != nil {
				_m.VenueID = *value
			}
		case match.FieldMatchDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field match_date", values[i])
			} else if value.Valid {
				_m.MatchDate = value.Time
			}
		case match.FieldStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_time", values[i])
			} else if value.Valid {
				_m.StartTime = value.Time
			}
		case match.FieldDurationHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_hours", values[i])
			} else if value.Valid {
				_m.DurationHours = value.Float64
			}
		case match.FieldMaxPlayers:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_players", values[i])
			} else if value.Valid {
				_m.MaxPlayers = int(value.Int64)
			}
		case match.FieldCurrentPlayers:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_players", values[i])
			} else if value.Valid {
				_m.CurrentPlayers = int(value.Int64)
			}
		case match.FieldCostPerPlayer:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_per_player", values[i])
			} else if value.Valid {
				_m.CostPerPlayer = int(value.Int64)
			}
		case match.FieldSkillLevelRequired:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill_level_required", values[i])
			} else if value.Valid {
				_m.SkillLevelRequired = match.SkillLevelRequired(value.String)
			}
		case match.FieldMatchType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_type", values[i])
			} else if value.Valid {
				_m.MatchType = match.MatchType(value.String)
			}
		case match.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = match.Status(value.String)
			}
		case match.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = match.Visibility(value.String)
			}
		case match.FieldRulesNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rules_notes", values[i])
			} else if value.Valid {
				_m.RulesNotes = value.String
			}
		case match.FieldReminderSent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field reminder_sent", values[i])
			} else if value.Valid {
				_m.ReminderSent = value.Bool
			}
		case match.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case match.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case match.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_created_matches", values[i])
			} else if value.Valid {
				_m.user_created_matches = new(uuid.UUID)
				*_m.user_created_matches = *value.S.(*uuid.UUID)
			}
		case match.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field venue_matches", values[i])
			} else if value.Valid {
				_m.venue_matches = new(uuid.UUID)
				*_m.venue_matches = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Match.
// This includes values selected through modifiers, order, etc.
func (_m *Match) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the Match entity.
func (_m *Match) QueryCreator() *UserQuery {
	return NewMatchClient(_m.config).QueryCreator(_m)
}

// QueryVenue queries the "venue" edge of the Match entity.
func (_m *Match) QueryVenue() *VenueQuery {
	return NewMatchClient(_m.config).QueryVenue(_m)
}

// QueryParticipants queries the "participants" edge of the Match entity.
func (_m *Match) QueryParticipants() *MatchParticipantQuery {
	return NewMatchClient(_m.config).QueryParticipants(_m)
}

// QueryNotifications queries the "notifications" edge of the Match entity.
func (_m *Match) QueryNotifications() *NotificationQuery {
	return NewMatchClient(_m.config).QueryNotifications(_m)
}

// Update returns a builder for updating this Match.
// Note that you need to call Match.Unwrap() before calling this method if this Match
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Match) Update() *MatchUpdateOne {
	return NewMatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Match entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Match) Unwrap() *Match {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Match is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Match) String() string {
	var builder strings.Builder
	builder.WriteString("Match(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("creator_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatorID))
	builder.WriteString(", ")
	builder.WriteString("venue_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VenueID))
	builder.WriteString(", ")
	builder.WriteString("match_date=")
	builder.WriteString(_m.MatchDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("start_time=")
	builder.WriteString(_m.StartTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("duration_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationHours))
	builder.WriteString(", ")
	builder.WriteString("max_players=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxPlayers))
	builder.WriteString(", ")
	builder.WriteString("current_players=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentPlayers))
	builder.WriteString(", ")
	builder.WriteString("cost_per_player=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostPerPlayer))
	builder.WriteString(", ")
	builder.WriteString("skill_level_required=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillLevelRequired))
	builder.WriteString(", ")
	builder.WriteString("match_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.MatchType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(fmt.Sprintf("%v", _m.Visibility))
	builder.WriteString(", ")
	builder.WriteString("rules_notes=")
	builder.WriteString(_m.RulesNotes)
	builder.WriteString(", ")
	builder.WriteString("reminder_sent=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReminderSent))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Matches is a parsable slice of Match.
type Matches []*Match
