// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kicknroar/internal/ent/match"
	"kicknroar/internal/ent/matchparticipant"
	"kicknroar/internal/ent/predicate"
	"kicknroar/internal/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MatchParticipantUpdate is the builder for updating MatchParticipant entities.
type MatchParticipantUpdate struct {
	config
	hooks    []Hook
	mutation *MatchParticipantMutation
}

// Where appends a list predicates to the MatchParticipantUpdate builder.
func (_u *MatchParticipantUpdate) Where(ps ...predicate.MatchParticipant) *MatchParticipantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMatchID sets the "match_id" field.
func (_u *MatchParticipantUpdate) SetMatchID(v uuid.UUID) *MatchParticipantUpdate {
	_u.mutation.SetMatchID(v)
	return _u
}

// SetNillableMatchID sets the "match_id" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillableMatchID(v *uuid.UUID) *MatchParticipantUpdate {
	if v != nil {
		_u.SetMatchID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MatchParticipantUpdate) SetUserID(v uuid.UUID) *MatchParticipantUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillableUserID(v *uuid.UUID) *MatchParticipantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *MatchParticipantUpdate) SetJoinedAt(v time.Time) *MatchParticipantUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillableJoinedAt(v *time.Time) *MatchParticipantUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetPaymentStatus sets the "payment_status" field.
func (_u *MatchParticipantUpdate) SetPaymentStatus(v matchparticipant.PaymentStatus) *MatchParticipantUpdate {
	_u.mutation.SetPaymentStatus(v)
	return _u
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillablePaymentStatus(v *matchparticipant.PaymentStatus) *MatchParticipantUpdate {
	if v != nil {
		_u.SetPaymentStatus(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *MatchParticipantUpdate) SetPaymentMethod(v string) *MatchParticipantUpdate {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillablePaymentMethod(v *string) *MatchParticipantUpdate {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (_u *MatchParticipantUpdate) ClearPaymentMethod() *MatchParticipantUpdate {
	_u.mutation.ClearPaymentMethod()
	return _u
}

// SetPaymentTransactionID sets the "payment_transaction_id" field.
func (_u *MatchParticipantUpdate) SetPaymentTransactionID(v string) *MatchParticipantUpdate {
	_u.mutation.SetPaymentTransactionID(v)
	return _u
}

// SetNillablePaymentTransactionID sets the "payment_transaction_id" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillablePaymentTransactionID(v *string) *MatchParticipantUpdate {
	if v != nil {
		_u.SetPaymentTransactionID(*v)
	}
	return _u
}

// ClearPaymentTransactionID clears the value of the "payment_transaction_id" field.
func (_u *MatchParticipantUpdate) ClearPaymentTransactionID() *MatchParticipantUpdate {
	_u.mutation.ClearPaymentTransactionID()
	return _u
}

// SetAttendanceStatus sets the "attendance_status" field.
func (_u *MatchParticipantUpdate) SetAttendanceStatus(v matchparticipant.AttendanceStatus) *MatchParticipantUpdate {
	_u.mutation.SetAttendanceStatus(v)
	return _u
}

// SetNillableAttendanceStatus sets the "attendance_status" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillableAttendanceStatus(v *matchparticipant.AttendanceStatus) *MatchParticipantUpdate {
	if v != nil {
		_u.SetAttendanceStatus(*v)
	}
	return _u
}

// SetPlayerRating sets the "player_rating" field.
func (_u *MatchParticipantUpdate) SetPlayerRating(v int) *MatchParticipantUpdate {
	_u.mutation.ResetPlayerRating()
	_u.mutation.SetPlayerRating(v)
	return _u
}

// SetNillablePlayerRating sets the "player_rating" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillablePlayerRating(v *int) *MatchParticipantUpdate {
	if v != nil {
		_u.SetPlayerRating(*v)
	}
	return _u
}

// AddPlayerRating adds value to the "player_rating" field.
func (_u *MatchParticipantUpdate) AddPlayerRating(v int) *MatchParticipantUpdate {
	_u.mutation.AddPlayerRating(v)
	return _u
}

// ClearPlayerRating clears the value of the "player_rating" field.
func (_u *MatchParticipantUpdate) ClearPlayerRating() *MatchParticipantUpdate {
	_u.mutation.ClearPlayerRating()
	return _u
}

// SetMatchRating sets the "match_rating" field.
func (_u *MatchParticipantUpdate) SetMatchRating(v int) *MatchParticipantUpdate {
	_u.mutation.ResetMatchRating()
	_u.mutation.SetMatchRating(v)
	return _u
}

// SetNillableMatchRating sets the "match_rating" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillableMatchRating(v *int) *MatchParticipantUpdate {
	if v != nil {
		_u.SetMatchRating(*v)
	}
	return _u
}

// AddMatchRating adds value to the "match_rating" field.
func (_u *MatchParticipantUpdate) AddMatchRating(v int) *MatchParticipantUpdate {
	_u.mutation.AddMatchRating(v)
	return _u
}

// ClearMatchRating clears the value of the "match_rating" field.
func (_u *MatchParticipantUpdate) ClearMatchRating() *MatchParticipantUpdate {
	_u.mutation.ClearMatchRating()
	return _u
}

// SetFeedback sets the "feedback" field.
func (_u *MatchParticipantUpdate) SetFeedback(v string) *MatchParticipantUpdate {
	_u.mutation.SetFeedback(v)
	return _u
}

// SetNillableFeedback sets the "feedback" field if the given value is not nil.
func (_u *MatchParticipantUpdate) SetNillableFeedback(v *string) *MatchParticipantUpdate {
	if v != nil {
		_u.SetFeedback(*v)
	}
	return _u
}

// ClearFeedback clears the value of the "feedback" field.
func (_u *MatchParticipantUpdate) ClearFeedback() *MatchParticipantUpdate {
	_u.mutation.ClearFeedback()
	return _u
}

// SetMatch sets the "match" edge to the Match entity.
func (_u *MatchParticipantUpdate) SetMatch(v *Match) *MatchParticipantUpdate {
	return _u.SetMatchID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *MatchParticipantUpdate) SetUser(v *User) *MatchParticipantUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MatchParticipantMutation object of the builder.
func (_u *MatchParticipantUpdate) Mutation() *MatchParticipantMutation {
	return _u.mutation
}

// ClearMatch clears the "match" edge to the Match entity.
func (_u *MatchParticipantUpdate) ClearMatch() *MatchParticipantUpdate {
	_u.mutation.ClearMatch()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MatchParticipantUpdate) ClearUser() *MatchParticipantUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MatchParticipantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatchParticipantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MatchParticipantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatchParticipantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatchParticipantUpdate) check() error {
	if v, ok := _u.mutation.PaymentStatus(); ok {
		if err := matchparticipant.PaymentStatusValidator(v); err != nil {
			return &ValidationError{Name: "payment_status", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.payment_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := matchparticipant.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentTransactionID(); ok {
		if err := matchparticipant.PaymentTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_transaction_id", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.payment_transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttendanceStatus(); ok {
		if err := matchparticipant.AttendanceStatusValidator(v); err != nil {
			return &ValidationError{Name: "attendance_status", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.attendance_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlayerRating(); ok {
		if err := matchparticipant.PlayerRatingValidator(v); err != nil {
			return &ValidationError{Name: "player_rating", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.player_rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchRating(); ok {
		if err := matchparticipant.MatchRatingValidator(v); err != nil {
			return &ValidationError{Name: "match_rating", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.match_rating": %w`, err)}
		}
	}
	if _u.mutation.MatchCleared() && len(_u.mutation.MatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MatchParticipant.match"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MatchParticipant.user"`)
	}
	return nil
}

func (_u *MatchParticipantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(matchparticipant.Table, matchparticipant.Columns, sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(matchparticipant.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaymentStatus(); ok {
		_spec.SetField(matchparticipant.FieldPaymentStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(matchparticipant.FieldPaymentMethod, field.TypeString, value)
	}
	if _u.mutation.PaymentMethodCleared() {
		_spec.ClearField(matchparticipant.FieldPaymentMethod, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentTransactionID(); ok {
		_spec.SetField(matchparticipant.FieldPaymentTransactionID, field.TypeString, value)
	}
	if _u.mutation.PaymentTransactionIDCleared() {
		_spec.ClearField(matchparticipant.FieldPaymentTransactionID, field.TypeString)
	}
	if value, ok := _u.mutation.AttendanceStatus(); ok {
		_spec.SetField(matchparticipant.FieldAttendanceStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PlayerRating(); ok {
		_spec.SetField(matchparticipant.FieldPlayerRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayerRating(); ok {
		_spec.AddField(matchparticipant.FieldPlayerRating, field.TypeInt, value)
	}
	if _u.mutation.PlayerRatingCleared() {
		_spec.ClearField(matchparticipant.FieldPlayerRating, field.TypeInt)
	}
	if value, ok := _u.mutation.MatchRating(); ok {
		_spec.SetField(matchparticipant.FieldMatchRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMatchRating(); ok {
		_spec.AddField(matchparticipant.FieldMatchRating, field.TypeInt, value)
	}
	if _u.mutation.MatchRatingCleared() {
		_spec.ClearField(matchparticipant.FieldMatchRating, field.TypeInt)
	}
	if value, ok := _u.mutation.Feedback(); ok {
		_spec.SetField(matchparticipant.FieldFeedback, field.TypeString, value)
	}
	if _u.mutation.FeedbackCleared() {
		_spec.ClearField(matchparticipant.FieldFeedback, field.TypeString)
	}
	if _u.mutation.MatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   matchparticipant.MatchTable,
			Columns: []string{matchparticipant.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   matchparticipant.MatchTable,
			Columns: []string{matchparticipant.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   matchparticipant.UserTable,
			Columns: []string{matchparticipant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   matchparticipant.UserTable,
			Columns: []string{matchparticipant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matchparticipant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MatchParticipantUpdateOne is the builder for updating a single MatchParticipant entity.
type MatchParticipantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MatchParticipantMutation
}

// SetMatchID sets the "match_id" field.
func (_u *MatchParticipantUpdateOne) SetMatchID(v uuid.UUID) *MatchParticipantUpdateOne {
	_u.mutation.SetMatchID(v)
	return _u
}

// SetNillableMatchID sets the "match_id" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillableMatchID(v *uuid.UUID) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetMatchID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MatchParticipantUpdateOne) SetUserID(v uuid.UUID) *MatchParticipantUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillableUserID(v *uuid.UUID) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *MatchParticipantUpdateOne) SetJoinedAt(v time.Time) *MatchParticipantUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillableJoinedAt(v *time.Time) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetPaymentStatus sets the "payment_status" field.
func (_u *MatchParticipantUpdateOne) SetPaymentStatus(v matchparticipant.PaymentStatus) *MatchParticipantUpdateOne {
	_u.mutation.SetPaymentStatus(v)
	return _u
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillablePaymentStatus(v *matchparticipant.PaymentStatus) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetPaymentStatus(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *MatchParticipantUpdateOne) SetPaymentMethod(v string) *MatchParticipantUpdateOne {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillablePaymentMethod(v *string) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (_u *MatchParticipantUpdateOne) ClearPaymentMethod() *MatchParticipantUpdateOne {
	_u.mutation.ClearPaymentMethod()
	return _u
}

// SetPaymentTransactionID sets the "payment_transaction_id" field.
func (_u *MatchParticipantUpdateOne) SetPaymentTransactionID(v string) *MatchParticipantUpdateOne {
	_u.mutation.SetPaymentTransactionID(v)
	return _u
}

// SetNillablePaymentTransactionID sets the "payment_transaction_id" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillablePaymentTransactionID(v *string) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetPaymentTransactionID(*v)
	}
	return _u
}

// ClearPaymentTransactionID clears the value of the "payment_transaction_id" field.
func (_u *MatchParticipantUpdateOne) ClearPaymentTransactionID() *MatchParticipantUpdateOne {
	_u.mutation.ClearPaymentTransactionID()
	return _u
}

// SetAttendanceStatus sets the "attendance_status" field.
func (_u *MatchParticipantUpdateOne) SetAttendanceStatus(v matchparticipant.AttendanceStatus) *MatchParticipantUpdateOne {
	_u.mutation.SetAttendanceStatus(v)
	return _u
}

// SetNillableAttendanceStatus sets the "attendance_status" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillableAttendanceStatus(v *matchparticipant.AttendanceStatus) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetAttendanceStatus(*v)
	}
	return _u
}

// SetPlayerRating sets the "player_rating" field.
func (_u *MatchParticipantUpdateOne) SetPlayerRating(v int) *MatchParticipantUpdateOne {
	_u.mutation.ResetPlayerRating()
	_u.mutation.SetPlayerRating(v)
	return _u
}

// SetNillablePlayerRating sets the "player_rating" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillablePlayerRating(v *int) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetPlayerRating(*v)
	}
	return _u
}

// AddPlayerRating adds value to the "player_rating" field.
func (_u *MatchParticipantUpdateOne) AddPlayerRating(v int) *MatchParticipantUpdateOne {
	_u.mutation.AddPlayerRating(v)
	return _u
}

// ClearPlayerRating clears the value of the "player_rating" field.
func (_u *MatchParticipantUpdateOne) ClearPlayerRating() *MatchParticipantUpdateOne {
	_u.mutation.ClearPlayerRating()
	return _u
}

// SetMatchRating sets the "match_rating" field.
func (_u *MatchParticipantUpdateOne) SetMatchRating(v int) *MatchParticipantUpdateOne {
	_u.mutation.ResetMatchRating()
	_u.mutation.SetMatchRating(v)
	return _u
}

// SetNillableMatchRating sets the "match_rating" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillableMatchRating(v *int) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetMatchRating(*v)
	}
	return _u
}

// AddMatchRating adds value to the "match_rating" field.
func (_u *MatchParticipantUpdateOne) AddMatchRating(v int) *MatchParticipantUpdateOne {
	_u.mutation.AddMatchRating(v)
	return _u
}

// ClearMatchRating clears the value of the "match_rating" field.
func (_u *MatchParticipantUpdateOne) ClearMatchRating() *MatchParticipantUpdateOne {
	_u.mutation.ClearMatchRating()
	return _u
}

// SetFeedback sets the "feedback" field.
func (_u *MatchParticipantUpdateOne) SetFeedback(v string) *MatchParticipantUpdateOne {
	_u.mutation.SetFeedback(v)
	return _u
}

// SetNillableFeedback sets the "feedback" field if the given value is not nil.
func (_u *MatchParticipantUpdateOne) SetNillableFeedback(v *string) *MatchParticipantUpdateOne {
	if v != nil {
		_u.SetFeedback(*v)
	}
	return _u
}

// ClearFeedback clears the value of the "feedback" field.
func (_u *MatchParticipantUpdateOne) ClearFeedback() *MatchParticipantUpdateOne {
	_u.mutation.ClearFeedback()
	return _u
}

// SetMatch sets the "match" edge to the Match entity.
func (_u *MatchParticipantUpdateOne) SetMatch(v *Match) *MatchParticipantUpdateOne {
	return _u.SetMatchID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *MatchParticipantUpdateOne) SetUser(v *User) *MatchParticipantUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MatchParticipantMutation object of the builder.
func (_u *MatchParticipantUpdateOne) Mutation() *MatchParticipantMutation {
	return _u.mutation
}

// ClearMatch clears the "match" edge to the Match entity.
func (_u *MatchParticipantUpdateOne) ClearMatch() *MatchParticipantUpdateOne {
	_u.mutation.ClearMatch()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MatchParticipantUpdateOne) ClearUser() *MatchParticipantUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the MatchParticipantUpdate builder.
func (_u *MatchParticipantUpdateOne) Where(ps ...predicate.MatchParticipant) *MatchParticipantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MatchParticipantUpdateOne) Select(field string, fields ...string) *MatchParticipantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MatchParticipant entity.
func (_u *MatchParticipantUpdateOne) Save(ctx context.Context) (*MatchParticipant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatchParticipantUpdateOne) SaveX(ctx context.Context) *MatchParticipant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MatchParticipantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatchParticipantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatchParticipantUpdateOne) check() error {
	if v, ok := _u.mutation.PaymentStatus(); ok {
		if err := matchparticipant.PaymentStatusValidator(v); err != nil {
			return &ValidationError{Name: "payment_status", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.payment_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := matchparticipant.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentTransactionID(); ok {
		if err := matchparticipant.PaymentTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_transaction_id", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.payment_transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttendanceStatus(); ok {
		if err := matchparticipant.AttendanceStatusValidator(v); err != nil {
			return &ValidationError{Name: "attendance_status", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.attendance_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlayerRating(); ok {
		if err := matchparticipant.PlayerRatingValidator(v); err != nil {
			return &ValidationError{Name: "player_rating", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.player_rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchRating(); ok {
		if err := matchparticipant.MatchRatingValidator(v); err != nil {
			return &ValidationError{Name: "match_rating", err: fmt.Errorf(`ent: validator failed for field "MatchParticipant.match_rating": %w`, err)}
		}
	}
	if _u.mutation.MatchCleared() && len(_u.mutation.MatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MatchParticipant.match"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MatchParticipant.user"`)
	}
	return nil
}

func (_u *MatchParticipantUpdateOne) sqlSave(ctx context.Context) (_node *MatchParticipant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(matchparticipant.Table, matchparticipant.Columns, sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MatchParticipant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, matchparticipant.FieldID)
		for _, f := range fields {
			if !matchparticipant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != matchparticipant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(matchparticipant.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaymentStatus(); ok {
		_spec.SetField(matchparticipant.FieldPaymentStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(matchparticipant.FieldPaymentMethod, field.TypeString, value)
	}
	if _u.mutation.PaymentMethodCleared() {
		_spec.ClearField(matchparticipant.FieldPaymentMethod, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentTransactionID(); ok {
		_spec.SetField(matchparticipant.FieldPaymentTransactionID, field.TypeString, value)
	}
	if _u.mutation.PaymentTransactionIDCleared() {
		_spec.ClearField(matchparticipant.FieldPaymentTransactionID, field.TypeString)
	}
	if value, ok := _u.mutation.AttendanceStatus(); ok {
		_spec.SetField(matchparticipant.FieldAttendanceStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PlayerRating(); ok {
		_spec.SetField(matchparticipant.FieldPlayerRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayerRating(); ok {
		_spec.AddField(matchparticipant.FieldPlayerRating, field.TypeInt, value)
	}
	if _u.mutation.PlayerRatingCleared() {
		_spec.ClearField(matchparticipant.FieldPlayerRating, field.TypeInt)
	}
	if value, ok := _u.mutation.MatchRating(); ok {
		_spec.SetField(matchparticipant.FieldMatchRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMatchRating(); ok {
		_spec.AddField(matchparticipant.FieldMatchRating, field.TypeInt, value)
	}
	if _u.mutation.MatchRatingCleared() {
		_spec.ClearField(matchparticipant.FieldMatchRating, field.TypeInt)
	}
	if value, ok := _u.mutation.Feedback(); ok {
		_spec.SetField(matchparticipant.FieldFeedback, field.TypeString, value)
	}
	if _u.mutation.FeedbackCleared() {
		_spec.ClearField(matchparticipant.FieldFeedback, field.TypeString)
	}
	if _u.mutation.MatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   matchparticipant.MatchTable,
			Columns: []string{matchparticipant.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   matchparticipant.MatchTable,
			Columns: []string{matchparticipant.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   matchparticipant.UserTable,
			Columns: []string{matchparticipant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   matchparticipant.UserTable,
			Columns: []string{matchparticipant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MatchParticipant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matchparticipant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
