// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kicknroar/internal/ent/match"
	"kicknroar/internal/ent/matchparticipant"
	"kicknroar/internal/ent/notification"
	"kicknroar/internal/ent/user"
	"kicknroar/internal/ent/venue"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MatchCreate is the builder for creating a Match entity.
type MatchCreate struct {
	config
	mutation *MatchMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *MatchCreate) SetTitle(v string) *MatchCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *MatchCreate) SetDescription(v string) *MatchCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MatchCreate) SetNillableDescription(v *string) *MatchCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatorID sets the "creator_id" field.
func (_c *MatchCreate) SetCreatorID(v uuid.UUID) *MatchCreate {
	_c.mutation.SetCreatorID(v)
	return _c
}

// SetVenueID sets the "venue_id" field.
func (_c *MatchCreate) SetVenueID(v uuid.UUID) *MatchCreate {
	_c.mutation.SetVenueID(v)
	return _c
}

// SetMatchDate sets the "match_date" field.
func (_c *MatchCreate) SetMatchDate(v time.Time) *MatchCreate {
	_c.mutation.SetMatchDate(v)
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *MatchCreate) SetStartTime(v time.Time) *MatchCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetDurationHours sets the "duration_hours" field.
func (_c *MatchCreate) SetDurationHours(v float64) *MatchCreate {
	_c.mutation.SetDurationHours(v)
	return _c
}

// SetNillableDurationHours sets the "duration_hours" field if the given value is not nil.
func (_c *MatchCreate) SetNillableDurationHours(v *float64) *MatchCreate {
	if v != nil {
		_c.SetDurationHours(*v)
	}
	return _c
}

// SetMaxPlayers sets the "max_players" field.
func (_c *MatchCreate) SetMaxPlayers(v int) *MatchCreate {
	_c.mutation.SetMaxPlayers(v)
	return _c
}

// SetNillableMaxPlayers sets the "max_players" field if the given value is not nil.
func (_c *MatchCreate) SetNillableMaxPlayers(v *int) *MatchCreate {
	if v != nil {
		_c.SetMaxPlayers(*v)
	}
	return _c
}

// SetCurrentPlayers sets the "current_players" field.
func (_c *MatchCreate) SetCurrentPlayers(v int) *MatchCreate {
	_c.mutation.SetCurrentPlayers(v)
	return _c
}

// SetNillableCurrentPlayers sets the "current_players" field if the given value is not nil.
func (_c *MatchCreate) SetNillableCurrentPlayers(v *int) *MatchCreate {
	if v != nil {
		_c.SetCurrentPlayers(*v)
	}
	return _c
}

// SetCostPerPlayer sets the "cost_per_player" field.
func (_c *MatchCreate) SetCostPerPlayer(v int) *MatchCreate {
	_c.mutation.SetCostPerPlayer(v)
	return _c
}

// SetSkillLevelRequired sets the "skill_level_required" field.
func (_c *MatchCreate) SetSkillLevelRequired(v match.SkillLevelRequired) *MatchCreate {
	_c.mutation.SetSkillLevelRequired(v)
	return _c
}

// SetNillableSkillLevelRequired sets the "skill_level_required" field if the given value is not nil.
func (_c *MatchCreate) SetNillableSkillLevelRequired(v *match.SkillLevelRequired) *MatchCreate {
	if v != nil {
		_c.SetSkillLevelRequired(*v)
	}
	return _c
}

// SetMatchType sets the "match_type" field.
func (_c *MatchCreate) SetMatchType(v match.MatchType) *MatchCreate {
	_c.mutation.SetMatchType(v)
	return _c
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_c *MatchCreate) SetNillableMatchType(v *match.MatchType) *MatchCreate {
	if v != nil {
		_c.SetMatchType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MatchCreate) SetStatus(v match.Status) *MatchCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MatchCreate) SetNillableStatus(v *match.Status) *MatchCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *MatchCreate) SetVisibility(v match.Visibility) *MatchCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *MatchCreate) SetNillableVisibility(v *match.Visibility) *MatchCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetRulesNotes sets the "rules_notes" field.
func (_c *MatchCreate) SetRulesNotes(v string) *MatchCreate {
	_c.mutation.SetRulesNotes(v)
	return _c
}

// SetNillableRulesNotes sets the "rules_notes" field if the given value is not nil.
func (_c *MatchCreate) SetNillableRulesNotes(v *string) *MatchCreate {
	if v != nil {
		_c.SetRulesNotes(*v)
	}
	return _c
}

// SetReminderSent sets the "reminder_sent" field.
func (_c *MatchCreate) SetReminderSent(v bool) *MatchCreate {
	_c.mutation.SetReminderSent(v)
	return _c
}

// SetNillableReminderSent sets the "reminder_sent" field if the given value is not nil.
func (_c *MatchCreate) SetNillableReminderSent(v *bool) *MatchCreate {
	if v != nil {
		_c.SetReminderSent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MatchCreate) SetCreatedAt(v time.Time) *MatchCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MatchCreate) SetNillableCreatedAt(v *time.Time) *MatchCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MatchCreate) SetUpdatedAt(v time.Time) *MatchCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MatchCreate) SetNillableUpdatedAt(v *time.Time) *MatchCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MatchCreate) SetID(v uuid.UUID) *MatchCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MatchCreate) SetNillableID(v *uuid.UUID) *MatchCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *MatchCreate) SetCreator(v *User) *MatchCreate {
	return _c.SetCreatorID(v.ID)
}

// SetVenue sets the "venue" edge to the Venue entity.
func (_c *MatchCreate) SetVenue(v *Venue) *MatchCreate {
	return _c.SetVenueID(v.ID)
}

// AddParticipantIDs adds the "participants" edge to the MatchParticipant entity by IDs.
func (_c *MatchCreate) AddParticipantIDs(ids ...uuid.UUID) *MatchCreate {
	_c.mutation.AddParticipantIDs(ids...)
	return _c
}

// AddParticipants adds the "participants" edges to the MatchParticipant entity.
func (_c *MatchCreate) AddParticipants(v ...*MatchParticipant) *MatchCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParticipantIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_c *MatchCreate) AddNotificationIDs(ids ...uuid.UUID) *MatchCreate {
	_c.mutation.AddNotificationIDs(ids...)
	return _c
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_c *MatchCreate) AddNotifications(v ...*Notification) *MatchCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotificationIDs(ids...)
}

// Mutation returns the MatchMutation object of the builder.
func (_c *MatchCreate) Mutation() *MatchMutation {
	return _c.mutation
}

// Save creates the Match in the database.
func (_c *MatchCreate) Save(ctx context.Context) (*Match, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MatchCreate) SaveX(ctx context.Context) *Match {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MatchCreate) defaults() {
	if _, ok := _c.mutation.DurationHours(); !ok {
		v := match.DefaultDurationHours
		_c.mutation.SetDurationHours(v)
	}
	if _, ok := _c.mutation.MaxPlayers(); !ok {
		v := match.DefaultMaxPlayers
		_c.mutation.SetMaxPlayers(v)
	}
	if _, ok := _c.mutation.CurrentPlayers(); !ok {
		v := match.DefaultCurrentPlayers
		_c.mutation.SetCurrentPlayers(v)
	}
	if _, ok := _c.mutation.MatchType(); !ok {
		v := match.DefaultMatchType
		_c.mutation.SetMatchType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := match.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := match.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.ReminderSent(); !ok {
		v := match.DefaultReminderSent
		_c.mutation.SetReminderSent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := match.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := match.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := match.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MatchCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Match.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := match.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Match.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatorID(); !ok {
		return &ValidationError{Name: "creator_id", err: errors.New(`ent: missing required field "Match.creator_id"`)}
	}
	if _, ok := _c.mutation.VenueID(); !ok {
		return &ValidationError{Name: "venue_id", err: errors.New(`ent: missing required field "Match.venue_id"`)}
	}
	if _, ok := _c.mutation.MatchDate(); !ok {
		return &ValidationError{Name: "match_date", err: errors.New(`ent: missing required field "Match.match_date"`)}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "Match.start_time"`)}
	}
	if _, ok := _c.mutation.DurationHours(); !ok {
		return &ValidationError{Name: "duration_hours", err: errors.New(`ent: missing required field "Match.duration_hours"`)}
	}
	if _, ok := _c.mutation.MaxPlayers(); !ok {
		return &ValidationError{Name: "max_players", err: errors.New(`ent: missing required field "Match.max_players"`)}
	}
	if v, ok := _c.mutation.MaxPlayers(); ok {
		if err := match.MaxPlayersValidator(v); err != nil {
			return &ValidationError{Name: "max_players", err: fmt.Errorf(`ent: validator failed for field "Match.max_players": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentPlayers(); !ok {
		return &ValidationError{Name: "current_players", err: errors.New(`ent: missing required field "Match.current_players"`)}
	}
	if v, ok := _c.mutation.CurrentPlayers(); ok {
		if err := match.CurrentPlayersValidator(v); err != nil {
			return &ValidationError{Name: "current_players", err: fmt.Errorf(`ent: validator failed for field "Match.current_players": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CostPerPlayer(); !ok {
		return &ValidationError{Name: "cost_per_player", err: errors.New(`ent: missing required field "Match.cost_per_player"`)}
	}
	if v, ok := _c.mutation.CostPerPlayer(); ok {
		if err := match.CostPerPlayerValidator(v); err != nil {
			return &ValidationError{Name: "cost_per_player", err: fmt.Errorf(`ent: validator failed for field "Match.cost_per_player": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SkillLevelRequired(); ok {
		if err := match.SkillLevelRequiredValidator(v); err != nil {
			return &ValidationError{Name: "skill_level_required", err: fmt.Errorf(`ent: validator failed for field "Match.skill_level_required": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MatchType(); !ok {
		return &ValidationError{Name: "match_type", err: errors.New(`ent: missing required field "Match.match_type"`)}
	}
	if v, ok := _c.mutation.MatchType(); ok {
		if err := match.MatchTypeValidator(v); err != nil {
			return &ValidationError{Name: "match_type", err: fmt.Errorf(`ent: validator failed for field "Match.match_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Match.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := match.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Match.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "Match.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := match.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Match.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReminderSent(); !ok {
		return &ValidationError{Name: "reminder_sent", err: errors.New(`ent: missing required field "Match.reminder_sent"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Match.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Match.updated_at"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Match.creator"`)}
	}
	if len(_c.mutation.VenueIDs()) == 0 {
		return &ValidationError{Name: "venue", err: errors.New(`ent: missing required edge "Match.venue"`)}
	}
	return nil
}

func (_c *MatchCreate) sqlSave(ctx context.Context) (*Match, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MatchCreate) createSpec() (*Match, *sqlgraph.CreateSpec) {
	var (
		_node = &Match{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(match.Table, sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(match.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(match.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.MatchDate(); ok {
		_spec.SetField(match.FieldMatchDate, field.TypeTime, value)
		_node.MatchDate = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(match.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.DurationHours(); ok {
		_spec.SetField(match.FieldDurationHours, field.TypeFloat64, value)
		_node.DurationHours = value
	}
	if value, ok := _c.mutation.MaxPlayers(); ok {
		_spec.SetField(match.FieldMaxPlayers, field.TypeInt, value)
		_node.MaxPlayers = value
	}
	if value, ok := _c.mutation.CurrentPlayers(); ok {
		_spec.SetField(match.FieldCurrentPlayers, field.TypeInt, value)
		_node.CurrentPlayers = value
	}
	if value, ok := _c.mutation.CostPerPlayer(); ok {
		_spec.SetField(match.FieldCostPerPlayer, field.TypeInt, value)
		_node.CostPerPlayer = value
	}
	if value, ok := _c.mutation.SkillLevelRequired(); ok {
		_spec.SetField(match.FieldSkillLevelRequired, field.TypeEnum, value)
		_node.SkillLevelRequired = value
	}
	if value, ok := _c.mutation.MatchType(); ok {
		_spec.SetField(match.FieldMatchType, field.TypeEnum, value)
		_node.MatchType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(match.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(match.FieldVisibility, field.TypeEnum, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.RulesNotes(); ok {
		_spec.SetField(match.FieldRulesNotes, field.TypeString, value)
		_node.RulesNotes = value
	}
	if value, ok := _c.mutation.ReminderSent(); ok {
		_spec.SetField(match.FieldReminderSent, field.TypeBool, value)
		_node.ReminderSent = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(match.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(match.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.CreatorTable,
			Columns: []string{match.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VenueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.VenueTable,
			Columns: []string{match.VenueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VenueID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.ParticipantsTable,
			Columns: []string{match.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.NotificationsTable,
			Columns: []string{match.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MatchCreateBulk is the builder for creating many Match entities in bulk.
type MatchCreateBulk struct {
	config
	err      error
	builders []*MatchCreate
}

// Save creates the Match entities in the database.
func (_c *MatchCreateBulk) Save(ctx context.Context) ([]*Match, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Match, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MatchCreateBulk) SaveX(ctx context.Context) []*Match {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
