// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kicknroar/internal/ent/match"
	"kicknroar/internal/ent/matchparticipant"
	"kicknroar/internal/ent/notification"
	"kicknroar/internal/ent/predicate"
	"kicknroar/internal/ent/user"
	"kicknroar/internal/ent/venue"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MatchUpdate is the builder for updating Match entities.
type MatchUpdate struct {
	config
	hooks    []Hook
	mutation *MatchMutation
}

// Where appends a list predicates to the MatchUpdate builder.
func (_u *MatchUpdate) Where(ps ...predicate.Match) *MatchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MatchUpdate) SetTitle(v string) *MatchUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableTitle(v *string) *MatchUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MatchUpdate) SetDescription(v string) *MatchUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableDescription(v *string) *MatchUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MatchUpdate) ClearDescription() *MatchUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *MatchUpdate) SetCreatorID(v uuid.UUID) *MatchUpdate {
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableCreatorID(v *uuid.UUID) *MatchUpdate {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// SetVenueID sets the "venue_id" field.
func (_u *MatchUpdate) SetVenueID(v uuid.UUID) *MatchUpdate {
	_u.mutation.SetVenueID(v)
	return _u
}

// SetNillableVenueID sets the "venue_id" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableVenueID(v *uuid.UUID) *MatchUpdate {
	if v != nil {
		_u.SetVenueID(*v)
	}
	return _u
}

// SetMatchDate sets the "match_date" field.
func (_u *MatchUpdate) SetMatchDate(v time.Time) *MatchUpdate {
	_u.mutation.SetMatchDate(v)
	return _u
}

// SetNillableMatchDate sets the "match_date" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableMatchDate(v *time.Time) *MatchUpdate {
	if v != nil {
		_u.SetMatchDate(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *MatchUpdate) SetStartTime(v time.Time) *MatchUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableStartTime(v *time.Time) *MatchUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetDurationHours sets the "duration_hours" field.
func (_u *MatchUpdate) SetDurationHours(v float64) *MatchUpdate {
	_u.mutation.ResetDurationHours()
	_u.mutation.SetDurationHours(v)
	return _u
}

// SetNillableDurationHours sets the "duration_hours" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableDurationHours(v *float64) *MatchUpdate {
	if v != nil {
		_u.SetDurationHours(*v)
	}
	return _u
}

// AddDurationHours adds value to the "duration_hours" field.
func (_u *MatchUpdate) AddDurationHours(v float64) *MatchUpdate {
	_u.mutation.AddDurationHours(v)
	return _u
}

// SetMaxPlayers sets the "max_players" field.
func (_u *MatchUpdate) SetMaxPlayers(v int) *MatchUpdate {
	_u.mutation.ResetMaxPlayers()
	_u.mutation.SetMaxPlayers(v)
	return _u
}

// SetNillableMaxPlayers sets the "max_players" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableMaxPlayers(v *int) *MatchUpdate {
	if v != nil {
		_u.SetMaxPlayers(*v)
	}
	return _u
}

// AddMaxPlayers adds value to the "max_players" field.
func (_u *MatchUpdate) AddMaxPlayers(v int) *MatchUpdate {
	_u.mutation.AddMaxPlayers(v)
	return _u
}

// SetCurrentPlayers sets the "current_players" field.
func (_u *MatchUpdate) SetCurrentPlayers(v int) *MatchUpdate {
	_u.mutation.ResetCurrentPlayers()
	_u.mutation.SetCurrentPlayers(v)
	return _u
}

// SetNillableCurrentPlayers sets the "current_players" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableCurrentPlayers(v *int) *MatchUpdate {
	if v != nil {
		_u.SetCurrentPlayers(*v)
	}
	return _u
}

// AddCurrentPlayers adds value to the "current_players" field.
func (_u *MatchUpdate) AddCurrentPlayers(v int) *MatchUpdate {
	_u.mutation.AddCurrentPlayers(v)
	return _u
}

// SetCostPerPlayer sets the "cost_per_player" field.
func (_u *MatchUpdate) SetCostPerPlayer(v int) *MatchUpdate {
	_u.mutation.ResetCostPerPlayer()
	_u.mutation.SetCostPerPlayer(v)
	return _u
}

// SetNillableCostPerPlayer sets the "cost_per_player" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableCostPerPlayer(v *int) *MatchUpdate {
	if v != nil {
		_u.SetCostPerPlayer(*v)
	}
	return _u
}

// AddCostPerPlayer adds value to the "cost_per_player" field.
func (_u *MatchUpdate) AddCostPerPlayer(v int) *MatchUpdate {
	_u.mutation.AddCostPerPlayer(v)
	return _u
}

// SetSkillLevelRequired sets the "skill_level_required" field.
func (_u *MatchUpdate) SetSkillLevelRequired(v match.SkillLevelRequired) *MatchUpdate {
	_u.mutation.SetSkillLevelRequired(v)
	return _u
}

// SetNillableSkillLevelRequired sets the "skill_level_required" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableSkillLevelRequired(v *match.SkillLevelRequired) *MatchUpdate {
	if v != nil {
		_u.SetSkillLevelRequired(*v)
	}
	return _u
}

// ClearSkillLevelRequired clears the value of the "skill_level_required" field.
func (_u *MatchUpdate) ClearSkillLevelRequired() *MatchUpdate {
	_u.mutation.ClearSkillLevelRequired()
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *MatchUpdate) SetMatchType(v match.MatchType) *MatchUpdate {
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableMatchType(v *match.MatchType) *MatchUpdate {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MatchUpdate) SetStatus(v match.Status) *MatchUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableStatus(v *match.Status) *MatchUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *MatchUpdate) SetVisibility(v match.Visibility) *MatchUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableVisibility(v *match.Visibility) *MatchUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetRulesNotes sets the "rules_notes" field.
func (_u *MatchUpdate) SetRulesNotes(v string) *MatchUpdate {
	_u.mutation.SetRulesNotes(v)
	return _u
}

// SetNillableRulesNotes sets the "rules_notes" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableRulesNotes(v *string) *MatchUpdate {
	if v != nil {
		_u.SetRulesNotes(*v)
	}
	return _u
}

// ClearRulesNotes clears the value of the "rules_notes" field.
func (_u *MatchUpdate) ClearRulesNotes() *MatchUpdate {
	_u.mutation.ClearRulesNotes()
	return _u
}

// SetReminderSent sets the "reminder_sent" field.
func (_u *MatchUpdate) SetReminderSent(v bool) *MatchUpdate {
	_u.mutation.SetReminderSent(v)
	return _u
}

// SetNillableReminderSent sets the "reminder_sent" field if the given value is not nil.
func (_u *MatchUpdate) SetNillableReminderSent(v *bool) *MatchUpdate {
	if v != nil {
		_u.SetReminderSent(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MatchUpdate) SetUpdatedAt(v time.Time) *MatchUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *MatchUpdate) SetCreator(v *User) *MatchUpdate {
	return _u.SetCreatorID(v.ID)
}

// SetVenue sets the "venue" edge to the Venue entity.
func (_u *MatchUpdate) SetVenue(v *Venue) *MatchUpdate {
	return _u.SetVenueID(v.ID)
}

// AddParticipantIDs adds the "participants" edge to the MatchParticipant entity by IDs.
func (_u *MatchUpdate) AddParticipantIDs(ids ...uuid.UUID) *MatchUpdate {
	_u.mutation.AddParticipantIDs(ids...)
	return _u
}

// AddParticipants adds the "participants" edges to the MatchParticipant entity.
func (_u *MatchUpdate) AddParticipants(v ...*MatchParticipant) *MatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipantIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *MatchUpdate) AddNotificationIDs(ids ...uuid.UUID) *MatchUpdate {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *MatchUpdate) AddNotifications(v ...*Notification) *MatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// Mutation returns the MatchMutation object of the builder.
func (_u *MatchUpdate) Mutation() *MatchMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *MatchUpdate) ClearCreator() *MatchUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearVenue clears the "venue" edge to the Venue entity.
func (_u *MatchUpdate) ClearVenue() *MatchUpdate {
	_u.mutation.ClearVenue()
	return _u
}

// ClearParticipants clears all "participants" edges to the MatchParticipant entity.
func (_u *MatchUpdate) ClearParticipants() *MatchUpdate {
	_u.mutation.ClearParticipants()
	return _u
}

// RemoveParticipantIDs removes the "participants" edge to MatchParticipant entities by IDs.
func (_u *MatchUpdate) RemoveParticipantIDs(ids ...uuid.UUID) *MatchUpdate {
	_u.mutation.RemoveParticipantIDs(ids...)
	return _u
}

// RemoveParticipants removes "participants" edges to MatchParticipant entities.
func (_u *MatchUpdate) RemoveParticipants(v ...*MatchParticipant) *MatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipantIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *MatchUpdate) ClearNotifications() *MatchUpdate {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *MatchUpdate) RemoveNotificationIDs(ids ...uuid.UUID) *MatchUpdate {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *MatchUpdate) RemoveNotifications(v ...*Notification) *MatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MatchUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MatchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MatchUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := match.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatchUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := match.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Match.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxPlayers(); ok {
		if err := match.MaxPlayersValidator(v); err != nil {
			return &ValidationError{Name: "max_players", err: fmt.Errorf(`ent: validator failed for field "Match.max_players": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentPlayers(); ok {
		if err := match.CurrentPlayersValidator(v); err != nil {
			return &ValidationError{Name: "current_players", err: fmt.Errorf(`ent: validator failed for field "Match.current_players": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostPerPlayer(); ok {
		if err := match.CostPerPlayerValidator(v); err != nil {
			return &ValidationError{Name: "cost_per_player", err: fmt.Errorf(`ent: validator failed for field "Match.cost_per_player": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkillLevelRequired(); ok {
		if err := match.SkillLevelRequiredValidator(v); err != nil {
			return &ValidationError{Name: "skill_level_required", err: fmt.Errorf(`ent: validator failed for field "Match.skill_level_required": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchType(); ok {
		if err := match.MatchTypeValidator(v); err != nil {
			return &ValidationError{Name: "match_type", err: fmt.Errorf(`ent: validator failed for field "Match.match_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := match.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Match.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := match.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Match.visibility": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Match.creator"`)
	}
	if _u.mutation.VenueCleared() && len(_u.mutation.VenueIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Match.venue"`)
	}
	return nil
}

func (_u *MatchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(match.Table, match.Columns, sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(match.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(match.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(match.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MatchDate(); ok {
		_spec.SetField(match.FieldMatchDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(match.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DurationHours(); ok {
		_spec.SetField(match.FieldDurationHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationHours(); ok {
		_spec.AddField(match.FieldDurationHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxPlayers(); ok {
		_spec.SetField(match.FieldMaxPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPlayers(); ok {
		_spec.AddField(match.FieldMaxPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentPlayers(); ok {
		_spec.SetField(match.FieldCurrentPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentPlayers(); ok {
		_spec.AddField(match.FieldCurrentPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostPerPlayer(); ok {
		_spec.SetField(match.FieldCostPerPlayer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostPerPlayer(); ok {
		_spec.AddField(match.FieldCostPerPlayer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SkillLevelRequired(); ok {
		_spec.SetField(match.FieldSkillLevelRequired, field.TypeEnum, value)
	}
	if _u.mutation.SkillLevelRequiredCleared() {
		_spec.ClearField(match.FieldSkillLevelRequired, field.TypeEnum)
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(match.FieldMatchType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(match.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(match.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RulesNotes(); ok {
		_spec.SetField(match.FieldRulesNotes, field.TypeString, value)
	}
	if _u.mutation.RulesNotesCleared() {
		_spec.ClearField(match.FieldRulesNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReminderSent(); ok {
		_spec.SetField(match.FieldReminderSent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(match.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.CreatorTable,
			Columns: []string{match.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.CreatorTable,
			Columns: []string{match.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VenueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.VenueTable,
			Columns: []string{match.VenueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VenueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.VenueTable,
			Columns: []string{match.VenueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.ParticipantsTable,
			Columns: []string{match.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipantsIDs(); len(nodes) > 0 && !_u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.ParticipantsTable,
			Columns: []string{match.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.ParticipantsTable,
			Columns: []string{match.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.NotificationsTable,
			Columns: []string{match.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.NotificationsTable,
			Columns: []string{match.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.NotificationsTable,
			Columns: []string{match.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{match.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MatchUpdateOne is the builder for updating a single Match entity.
type MatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MatchMutation
}

// SetTitle sets the "title" field.
func (_u *MatchUpdateOne) SetTitle(v string) *MatchUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableTitle(v *string) *MatchUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MatchUpdateOne) SetDescription(v string) *MatchUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableDescription(v *string) *MatchUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MatchUpdateOne) ClearDescription() *MatchUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *MatchUpdateOne) SetCreatorID(v uuid.UUID) *MatchUpdateOne {
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableCreatorID(v *uuid.UUID) *MatchUpdateOne {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// SetVenueID sets the "venue_id" field.
func (_u *MatchUpdateOne) SetVenueID(v uuid.UUID) *MatchUpdateOne {
	_u.mutation.SetVenueID(v)
	return _u
}

// SetNillableVenueID sets the "venue_id" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableVenueID(v *uuid.UUID) *MatchUpdateOne {
	if v != nil {
		_u.SetVenueID(*v)
	}
	return _u
}

// SetMatchDate sets the "match_date" field.
func (_u *MatchUpdateOne) SetMatchDate(v time.Time) *MatchUpdateOne {
	_u.mutation.SetMatchDate(v)
	return _u
}

// SetNillableMatchDate sets the "match_date" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableMatchDate(v *time.Time) *MatchUpdateOne {
	if v != nil {
		_u.SetMatchDate(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *MatchUpdateOne) SetStartTime(v time.Time) *MatchUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableStartTime(v *time.Time) *MatchUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetDurationHours sets the "duration_hours" field.
func (_u *MatchUpdateOne) SetDurationHours(v float64) *MatchUpdateOne {
	_u.mutation.ResetDurationHours()
	_u.mutation.SetDurationHours(v)
	return _u
}

// SetNillableDurationHours sets the "duration_hours" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableDurationHours(v *float64) *MatchUpdateOne {
	if v != nil {
		_u.SetDurationHours(*v)
	}
	return _u
}

// AddDurationHours adds value to the "duration_hours" field.
func (_u *MatchUpdateOne) AddDurationHours(v float64) *MatchUpdateOne {
	_u.mutation.AddDurationHours(v)
	return _u
}

// SetMaxPlayers sets the "max_players" field.
func (_u *MatchUpdateOne) SetMaxPlayers(v int) *MatchUpdateOne {
	_u.mutation.ResetMaxPlayers()
	_u.mutation.SetMaxPlayers(v)
	return _u
}

// SetNillableMaxPlayers sets the "max_players" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableMaxPlayers(v *int) *MatchUpdateOne {
	if v != nil {
		_u.SetMaxPlayers(*v)
	}
	return _u
}

// AddMaxPlayers adds value to the "max_players" field.
func (_u *MatchUpdateOne) AddMaxPlayers(v int) *MatchUpdateOne {
	_u.mutation.AddMaxPlayers(v)
	return _u
}

// SetCurrentPlayers sets the "current_players" field.
func (_u *MatchUpdateOne) SetCurrentPlayers(v int) *MatchUpdateOne {
	_u.mutation.ResetCurrentPlayers()
	_u.mutation.SetCurrentPlayers(v)
	return _u
}

// SetNillableCurrentPlayers sets the "current_players" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableCurrentPlayers(v *int) *MatchUpdateOne {
	if v != nil {
		_u.SetCurrentPlayers(*v)
	}
	return _u
}

// AddCurrentPlayers adds value to the "current_players" field.
func (_u *MatchUpdateOne) AddCurrentPlayers(v int) *MatchUpdateOne {
	_u.mutation.AddCurrentPlayers(v)
	return _u
}

// SetCostPerPlayer sets the "cost_per_player" field.
func (_u *MatchUpdateOne) SetCostPerPlayer(v int) *MatchUpdateOne {
	_u.mutation.ResetCostPerPlayer()
	_u.mutation.SetCostPerPlayer(v)
	return _u
}

// SetNillableCostPerPlayer sets the "cost_per_player" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableCostPerPlayer(v *int) *MatchUpdateOne {
	if v != nil {
		_u.SetCostPerPlayer(*v)
	}
	return _u
}

// AddCostPerPlayer adds value to the "cost_per_player" field.
func (_u *MatchUpdateOne) AddCostPerPlayer(v int) *MatchUpdateOne {
	_u.mutation.AddCostPerPlayer(v)
	return _u
}

// SetSkillLevelRequired sets the "skill_level_required" field.
func (_u *MatchUpdateOne) SetSkillLevelRequired(v match.SkillLevelRequired) *MatchUpdateOne {
	_u.mutation.SetSkillLevelRequired(v)
	return _u
}

// SetNillableSkillLevelRequired sets the "skill_level_required" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableSkillLevelRequired(v *match.SkillLevelRequired) *MatchUpdateOne {
	if v != nil {
		_u.SetSkillLevelRequired(*v)
	}
	return _u
}

// ClearSkillLevelRequired clears the value of the "skill_level_required" field.
func (_u *MatchUpdateOne) ClearSkillLevelRequired() *MatchUpdateOne {
	_u.mutation.ClearSkillLevelRequired()
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *MatchUpdateOne) SetMatchType(v match.MatchType) *MatchUpdateOne {
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableMatchType(v *match.MatchType) *MatchUpdateOne {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MatchUpdateOne) SetStatus(v match.Status) *MatchUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableStatus(v *match.Status) *MatchUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *MatchUpdateOne) SetVisibility(v match.Visibility) *MatchUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableVisibility(v *match.Visibility) *MatchUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetRulesNotes sets the "rules_notes" field.
func (_u *MatchUpdateOne) SetRulesNotes(v string) *MatchUpdateOne {
	_u.mutation.SetRulesNotes(v)
	return _u
}

// SetNillableRulesNotes sets the "rules_notes" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableRulesNotes(v *string) *MatchUpdateOne {
	if v != nil {
		_u.SetRulesNotes(*v)
	}
	return _u
}

// ClearRulesNotes clears the value of the "rules_notes" field.
func (_u *MatchUpdateOne) ClearRulesNotes() *MatchUpdateOne {
	_u.mutation.ClearRulesNotes()
	return _u
}

// SetReminderSent sets the "reminder_sent" field.
func (_u *MatchUpdateOne) SetReminderSent(v bool) *MatchUpdateOne {
	_u.mutation.SetReminderSent(v)
	return _u
}

// SetNillableReminderSent sets the "reminder_sent" field if the given value is not nil.
func (_u *MatchUpdateOne) SetNillableReminderSent(v *bool) *MatchUpdateOne {
	if v != nil {
		_u.SetReminderSent(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MatchUpdateOne) SetUpdatedAt(v time.Time) *MatchUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *MatchUpdateOne) SetCreator(v *User) *MatchUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// SetVenue sets the "venue" edge to the Venue entity.
func (_u *MatchUpdateOne) SetVenue(v *Venue) *MatchUpdateOne {
	return _u.SetVenueID(v.ID)
}

// AddParticipantIDs adds the "participants" edge to the MatchParticipant entity by IDs.
func (_u *MatchUpdateOne) AddParticipantIDs(ids ...uuid.UUID) *MatchUpdateOne {
	_u.mutation.AddParticipantIDs(ids...)
	return _u
}

// AddParticipants adds the "participants" edges to the MatchParticipant entity.
func (_u *MatchUpdateOne) AddParticipants(v ...*MatchParticipant) *MatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipantIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *MatchUpdateOne) AddNotificationIDs(ids ...uuid.UUID) *MatchUpdateOne {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *MatchUpdateOne) AddNotifications(v ...*Notification) *MatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// Mutation returns the MatchMutation object of the builder.
func (_u *MatchUpdateOne) Mutation() *MatchMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *MatchUpdateOne) ClearCreator() *MatchUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearVenue clears the "venue" edge to the Venue entity.
func (_u *MatchUpdateOne) ClearVenue() *MatchUpdateOne {
	_u.mutation.ClearVenue()
	return _u
}

// ClearParticipants clears all "participants" edges to the MatchParticipant entity.
func (_u *MatchUpdateOne) ClearParticipants() *MatchUpdateOne {
	_u.mutation.ClearParticipants()
	return _u
}

// RemoveParticipantIDs removes the "participants" edge to MatchParticipant entities by IDs.
func (_u *MatchUpdateOne) RemoveParticipantIDs(ids ...uuid.UUID) *MatchUpdateOne {
	_u.mutation.RemoveParticipantIDs(ids...)
	return _u
}

// RemoveParticipants removes "participants" edges to MatchParticipant entities.
func (_u *MatchUpdateOne) RemoveParticipants(v ...*MatchParticipant) *MatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipantIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *MatchUpdateOne) ClearNotifications() *MatchUpdateOne {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *MatchUpdateOne) RemoveNotificationIDs(ids ...uuid.UUID) *MatchUpdateOne {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *MatchUpdateOne) RemoveNotifications(v ...*Notification) *MatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// Where appends a list predicates to the MatchUpdate builder.
func (_u *MatchUpdateOne) Where(ps ...predicate.Match) *MatchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MatchUpdateOne) Select(field string, fields ...string) *MatchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Match entity.
func (_u *MatchUpdateOne) Save(ctx context.Context) (*Match, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatchUpdateOne) SaveX(ctx context.Context) *Match {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MatchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MatchUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := match.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatchUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := match.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Match.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxPlayers(); ok {
		if err := match.MaxPlayersValidator(v); err != nil {
			return &ValidationError{Name: "max_players", err: fmt.Errorf(`ent: validator failed for field "Match.max_players": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentPlayers(); ok {
		if err := match.CurrentPlayersValidator(v); err != nil {
			return &ValidationError{Name: "current_players", err: fmt.Errorf(`ent: validator failed for field "Match.current_players": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostPerPlayer(); ok {
		if err := match.CostPerPlayerValidator(v); err != nil {
			return &ValidationError{Name: "cost_per_player", err: fmt.Errorf(`ent: validator failed for field "Match.cost_per_player": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkillLevelRequired(); ok {
		if err := match.SkillLevelRequiredValidator(v); err != nil {
			return &ValidationError{Name: "skill_level_required", err: fmt.Errorf(`ent: validator failed for field "Match.skill_level_required": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchType(); ok {
		if err := match.MatchTypeValidator(v); err != nil {
			return &ValidationError{Name: "match_type", err: fmt.Errorf(`ent: validator failed for field "Match.match_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := match.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Match.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := match.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Match.visibility": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Match.creator"`)
	}
	if _u.mutation.VenueCleared() && len(_u.mutation.VenueIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Match.venue"`)
	}
	return nil
}

func (_u *MatchUpdateOne) sqlSave(ctx context.Context) (_node *Match, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(match.Table, match.Columns, sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Match.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, match.FieldID)
		for _, f := range fields {
			if !match.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != match.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(match.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(match.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(match.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MatchDate(); ok {
		_spec.SetField(match.FieldMatchDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(match.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DurationHours(); ok {
		_spec.SetField(match.FieldDurationHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationHours(); ok {
		_spec.AddField(match.FieldDurationHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxPlayers(); ok {
		_spec.SetField(match.FieldMaxPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPlayers(); ok {
		_spec.AddField(match.FieldMaxPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentPlayers(); ok {
		_spec.SetField(match.FieldCurrentPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentPlayers(); ok {
		_spec.AddField(match.FieldCurrentPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostPerPlayer(); ok {
		_spec.SetField(match.FieldCostPerPlayer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostPerPlayer(); ok {
		_spec.AddField(match.FieldCostPerPlayer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SkillLevelRequired(); ok {
		_spec.SetField(match.FieldSkillLevelRequired, field.TypeEnum, value)
	}
	if _u.mutation.SkillLevelRequiredCleared() {
		_spec.ClearField(match.FieldSkillLevelRequired, field.TypeEnum)
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(match.FieldMatchType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(match.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(match.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RulesNotes(); ok {
		_spec.SetField(match.FieldRulesNotes, field.TypeString, value)
	}
	if _u.mutation.RulesNotesCleared() {
		_spec.ClearField(match.FieldRulesNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReminderSent(); ok {
		_spec.SetField(match.FieldReminderSent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(match.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.CreatorTable,
			Columns: []string{match.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.CreatorTable,
			Columns: []string{match.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VenueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.VenueTable,
			Columns: []string{match.VenueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VenueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   match.VenueTable,
			Columns: []string{match.VenueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.ParticipantsTable,
			Columns: []string{match.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipantsIDs(); len(nodes) > 0 && !_u.mutation.ParticipantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.ParticipantsTable,
			Columns: []string{match.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.ParticipantsTable,
			Columns: []string{match.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.NotificationsTable,
			Columns: []string{match.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.NotificationsTable,
			Columns: []string{match.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   match.NotificationsTable,
			Columns: []string{match.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Match{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{match.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
