// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kicknroar/internal/ent/match"
	"kicknroar/internal/ent/notification"
	"kicknroar/internal/ent/predicate"
	"kicknroar/internal/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotificationUpdate) SetUserID(v uuid.UUID) *NotificationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableUserID(v *uuid.UUID) *NotificationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMatchID sets the "match_id" field.
func (_u *NotificationUpdate) SetMatchID(v uuid.UUID) *NotificationUpdate {
	_u.mutation.SetMatchID(v)
	return _u
}

// SetNillableMatchID sets the "match_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableMatchID(v *uuid.UUID) *NotificationUpdate {
	if v != nil {
		_u.SetMatchID(*v)
	}
	return _u
}

// ClearMatchID clears the value of the "match_id" field.
func (_u *NotificationUpdate) ClearMatchID() *NotificationUpdate {
	_u.mutation.ClearMatchID()
	return _u
}

// SetType sets the "type" field.
func (_u *NotificationUpdate) SetType(v notification.Type) *NotificationUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableType(v *notification.Type) *NotificationUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdate) SetTitle(v string) *NotificationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTitle(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationUpdate) SetMessage(v string) *NotificationUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableMessage(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetActionURL sets the "action_url" field.
func (_u *NotificationUpdate) SetActionURL(v string) *NotificationUpdate {
	_u.mutation.SetActionURL(v)
	return _u
}

// SetNillableActionURL sets the "action_url" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableActionURL(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetActionURL(*v)
	}
	return _u
}

// ClearActionURL clears the value of the "action_url" field.
func (_u *NotificationUpdate) ClearActionURL() *NotificationUpdate {
	_u.mutation.ClearActionURL()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdate) SetIsRead(v bool) *NotificationUpdate {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableIsRead(v *bool) *NotificationUpdate {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetIsSent sets the "is_sent" field.
func (_u *NotificationUpdate) SetIsSent(v bool) *NotificationUpdate {
	_u.mutation.SetIsSent(v)
	return _u
}

// SetNillableIsSent sets the "is_sent" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableIsSent(v *bool) *NotificationUpdate {
	if v != nil {
		_u.SetIsSent(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *NotificationUpdate) SetReadAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableReadAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *NotificationUpdate) ClearReadAt() *NotificationUpdate {
	_u.mutation.ClearReadAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NotificationUpdate) SetUser(v *User) *NotificationUpdate {
	return _u.SetUserID(v.ID)
}

// SetMatch sets the "match" edge to the Match entity.
func (_u *NotificationUpdate) SetMatch(v *Match) *NotificationUpdate {
	return _u.SetMatchID(v.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NotificationUpdate) ClearUser() *NotificationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearMatch clears the "match" edge to the Match entity.
func (_u *NotificationUpdate) ClearMatch() *NotificationUpdate {
	_u.mutation.ClearMatch()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := notification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Notification.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := notification.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Notification.message": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.user"`)
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionURL(); ok {
		_spec.SetField(notification.FieldActionURL, field.TypeString, value)
	}
	if _u.mutation.ActionURLCleared() {
		_spec.ClearField(notification.FieldActionURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSent(); ok {
		_spec.SetField(notification.FieldIsSent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(notification.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(notification.FieldReadAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.UserTable,
			Columns: []string{notification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.UserTable,
			Columns: []string{notification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.MatchTable,
			Columns: []string{notification.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.MatchTable,
			Columns: []string{notification.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetUserID sets the "user_id" field.
func (_u *NotificationUpdateOne) SetUserID(v uuid.UUID) *NotificationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableUserID(v *uuid.UUID) *NotificationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMatchID sets the "match_id" field.
func (_u *NotificationUpdateOne) SetMatchID(v uuid.UUID) *NotificationUpdateOne {
	_u.mutation.SetMatchID(v)
	return _u
}

// SetNillableMatchID sets the "match_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableMatchID(v *uuid.UUID) *NotificationUpdateOne {
	if v != nil {
		_u.SetMatchID(*v)
	}
	return _u
}

// ClearMatchID clears the value of the "match_id" field.
func (_u *NotificationUpdateOne) ClearMatchID() *NotificationUpdateOne {
	_u.mutation.ClearMatchID()
	return _u
}

// SetType sets the "type" field.
func (_u *NotificationUpdateOne) SetType(v notification.Type) *NotificationUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableType(v *notification.Type) *NotificationUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdateOne) SetTitle(v string) *NotificationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTitle(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationUpdateOne) SetMessage(v string) *NotificationUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableMessage(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetActionURL sets the "action_url" field.
func (_u *NotificationUpdateOne) SetActionURL(v string) *NotificationUpdateOne {
	_u.mutation.SetActionURL(v)
	return _u
}

// SetNillableActionURL sets the "action_url" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableActionURL(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetActionURL(*v)
	}
	return _u
}

// ClearActionURL clears the value of the "action_url" field.
func (_u *NotificationUpdateOne) ClearActionURL() *NotificationUpdateOne {
	_u.mutation.ClearActionURL()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdateOne) SetIsRead(v bool) *NotificationUpdateOne {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableIsRead(v *bool) *NotificationUpdateOne {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetIsSent sets the "is_sent" field.
func (_u *NotificationUpdateOne) SetIsSent(v bool) *NotificationUpdateOne {
	_u.mutation.SetIsSent(v)
	return _u
}

// SetNillableIsSent sets the "is_sent" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableIsSent(v *bool) *NotificationUpdateOne {
	if v != nil {
		_u.SetIsSent(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *NotificationUpdateOne) SetReadAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableReadAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *NotificationUpdateOne) ClearReadAt() *NotificationUpdateOne {
	_u.mutation.ClearReadAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NotificationUpdateOne) SetUser(v *User) *NotificationUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetMatch sets the "match" edge to the Match entity.
func (_u *NotificationUpdateOne) SetMatch(v *Match) *NotificationUpdateOne {
	return _u.SetMatchID(v.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NotificationUpdateOne) ClearUser() *NotificationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearMatch clears the "match" edge to the Match entity.
func (_u *NotificationUpdateOne) ClearMatch() *NotificationUpdateOne {
	_u.mutation.ClearMatch()
	return _u
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := notification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Notification.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := notification.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Notification.message": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.user"`)
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionURL(); ok {
		_spec.SetField(notification.FieldActionURL, field.TypeString, value)
	}
	if _u.mutation.ActionURLCleared() {
		_spec.ClearField(notification.FieldActionURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSent(); ok {
		_spec.SetField(notification.FieldIsSent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(notification.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(notification.FieldReadAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.UserTable,
			Columns: []string{notification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.UserTable,
			Columns: []string{notification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.MatchTable,
			Columns: []string{notification.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.MatchTable,
			Columns: []string{notification.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
