// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kicknroar/internal/ent/predicate"
	"kicknroar/internal/ent/user"
	"kicknroar/internal/ent/userstats"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserStatsUpdate is the builder for updating UserStats entities.
type UserStatsUpdate struct {
	config
	hooks    []Hook
	mutation *UserStatsMutation
}

// Where appends a list predicates to the UserStatsUpdate builder.
func (_u *UserStatsUpdate) Where(ps ...predicate.UserStats) *UserStatsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserStatsUpdate) SetUserID(v uuid.UUID) *UserStatsUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableUserID(v *uuid.UUID) *UserStatsUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTotalMatches sets the "total_matches" field.
func (_u *UserStatsUpdate) SetTotalMatches(v int) *UserStatsUpdate {
	_u.mutation.ResetTotalMatches()
	_u.mutation.SetTotalMatches(v)
	return _u
}

// SetNillableTotalMatches sets the "total_matches" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableTotalMatches(v *int) *UserStatsUpdate {
	if v != nil {
		_u.SetTotalMatches(*v)
	}
	return _u
}

// AddTotalMatches adds value to the "total_matches" field.
func (_u *UserStatsUpdate) AddTotalMatches(v int) *UserStatsUpdate {
	_u.mutation.AddTotalMatches(v)
	return _u
}

// SetMatchesAttended sets the "matches_attended" field.
func (_u *UserStatsUpdate) SetMatchesAttended(v int) *UserStatsUpdate {
	_u.mutation.ResetMatchesAttended()
	_u.mutation.SetMatchesAttended(v)
	return _u
}

// SetNillableMatchesAttended sets the "matches_attended" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableMatchesAttended(v *int) *UserStatsUpdate {
	if v != nil {
		_u.SetMatchesAttended(*v)
	}
	return _u
}

// AddMatchesAttended adds value to the "matches_attended" field.
func (_u *UserStatsUpdate) AddMatchesAttended(v int) *UserStatsUpdate {
	_u.mutation.AddMatchesAttended(v)
	return _u
}

// SetMatchesOrganized sets the "matches_organized" field.
func (_u *UserStatsUpdate) SetMatchesOrganized(v int) *UserStatsUpdate {
	_u.mutation.ResetMatchesOrganized()
	_u.mutation.SetMatchesOrganized(v)
	return _u
}

// SetNillableMatchesOrganized sets the "matches_organized" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableMatchesOrganized(v *int) *UserStatsUpdate {
	if v != nil {
		_u.SetMatchesOrganized(*v)
	}
	return _u
}

// AddMatchesOrganized adds value to the "matches_organized" field.
func (_u *UserStatsUpdate) AddMatchesOrganized(v int) *UserStatsUpdate {
	_u.mutation.AddMatchesOrganized(v)
	return _u
}

// SetNoShows sets the "no_shows" field.
func (_u *UserStatsUpdate) SetNoShows(v int) *UserStatsUpdate {
	_u.mutation.ResetNoShows()
	_u.mutation.SetNoShows(v)
	return _u
}

// SetNillableNoShows sets the "no_shows" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableNoShows(v *int) *UserStatsUpdate {
	if v != nil {
		_u.SetNoShows(*v)
	}
	return _u
}

// AddNoShows adds value to the "no_shows" field.
func (_u *UserStatsUpdate) AddNoShows(v int) *UserStatsUpdate {
	_u.mutation.AddNoShows(v)
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *UserStatsUpdate) SetAverageRating(v float64) *UserStatsUpdate {
	_u.mutation.ResetAverageRating()
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableAverageRating(v *float64) *UserStatsUpdate {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// AddAverageRating adds value to the "average_rating" field.
func (_u *UserStatsUpdate) AddAverageRating(v float64) *UserStatsUpdate {
	_u.mutation.AddAverageRating(v)
	return _u
}

// SetTotalRatingsReceived sets the "total_ratings_received" field.
func (_u *UserStatsUpdate) SetTotalRatingsReceived(v int) *UserStatsUpdate {
	_u.mutation.ResetTotalRatingsReceived()
	_u.mutation.SetTotalRatingsReceived(v)
	return _u
}

// SetNillableTotalRatingsReceived sets the "total_ratings_received" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableTotalRatingsReceived(v *int) *UserStatsUpdate {
	if v != nil {
		_u.SetTotalRatingsReceived(*v)
	}
	return _u
}

// AddTotalRatingsReceived adds value to the "total_ratings_received" field.
func (_u *UserStatsUpdate) AddTotalRatingsReceived(v int) *UserStatsUpdate {
	_u.mutation.AddTotalRatingsReceived(v)
	return _u
}

// SetReliabilityScore sets the "reliability_score" field.
func (_u *UserStatsUpdate) SetReliabilityScore(v float64) *UserStatsUpdate {
	_u.mutation.ResetReliabilityScore()
	_u.mutation.SetReliabilityScore(v)
	return _u
}

// SetNillableReliabilityScore sets the "reliability_score" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableReliabilityScore(v *float64) *UserStatsUpdate {
	if v != nil {
		_u.SetReliabilityScore(*v)
	}
	return _u
}

// AddReliabilityScore adds value to the "reliability_score" field.
func (_u *UserStatsUpdate) AddReliabilityScore(v float64) *UserStatsUpdate {
	_u.mutation.AddReliabilityScore(v)
	return _u
}

// SetLastMatchAt sets the "last_match_at" field.
func (_u *UserStatsUpdate) SetLastMatchAt(v time.Time) *UserStatsUpdate {
	_u.mutation.SetLastMatchAt(v)
	return _u
}

// SetNillableLastMatchAt sets the "last_match_at" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableLastMatchAt(v *time.Time) *UserStatsUpdate {
	if v != nil {
		_u.SetLastMatchAt(*v)
	}
	return _u
}

// ClearLastMatchAt clears the value of the "last_match_at" field.
func (_u *UserStatsUpdate) ClearLastMatchAt() *UserStatsUpdate {
	_u.mutation.ClearLastMatchAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserStatsUpdate) SetUpdatedAt(v time.Time) *UserStatsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserStatsUpdate) SetUser(v *User) *UserStatsUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserStatsMutation object of the builder.
func (_u *UserStatsUpdate) Mutation() *UserStatsMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserStatsUpdate) ClearUser() *UserStatsUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserStatsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserStatsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserStatsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserStatsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserStatsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userstats.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserStatsUpdate) check() error {
	if v, ok := _u.mutation.AverageRating(); ok {
		if err := userstats.AverageRatingValidator(v); err != nil {
			return &ValidationError{Name: "average_rating", err: fmt.Errorf(`ent: validator failed for field "UserStats.average_rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReliabilityScore(); ok {
		if err := userstats.ReliabilityScoreValidator(v); err != nil {
			return &ValidationError{Name: "reliability_score", err: fmt.Errorf(`ent: validator failed for field "UserStats.reliability_score": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserStats.user"`)
	}
	return nil
}

func (_u *UserStatsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userstats.Table, userstats.Columns, sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TotalMatches(); ok {
		_spec.SetField(userstats.FieldTotalMatches, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalMatches(); ok {
		_spec.AddField(userstats.FieldTotalMatches, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MatchesAttended(); ok {
		_spec.SetField(userstats.FieldMatchesAttended, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMatchesAttended(); ok {
		_spec.AddField(userstats.FieldMatchesAttended, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MatchesOrganized(); ok {
		_spec.SetField(userstats.FieldMatchesOrganized, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMatchesOrganized(); ok {
		_spec.AddField(userstats.FieldMatchesOrganized, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NoShows(); ok {
		_spec.SetField(userstats.FieldNoShows, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNoShows(); ok {
		_spec.AddField(userstats.FieldNoShows, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(userstats.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageRating(); ok {
		_spec.AddField(userstats.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRatingsReceived(); ok {
		_spec.SetField(userstats.FieldTotalRatingsReceived, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalRatingsReceived(); ok {
		_spec.AddField(userstats.FieldTotalRatingsReceived, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReliabilityScore(); ok {
		_spec.SetField(userstats.FieldReliabilityScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReliabilityScore(); ok {
		_spec.AddField(userstats.FieldReliabilityScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastMatchAt(); ok {
		_spec.SetField(userstats.FieldLastMatchAt, field.TypeTime, value)
	}
	if _u.mutation.LastMatchAtCleared() {
		_spec.ClearField(userstats.FieldLastMatchAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userstats.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userstats.UserTable,
			Columns: []string{userstats.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userstats.UserTable,
			Columns: []string{userstats.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserStatsUpdateOne is the builder for updating a single UserStats entity.
type UserStatsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserStatsMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserStatsUpdateOne) SetUserID(v uuid.UUID) *UserStatsUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableUserID(v *uuid.UUID) *UserStatsUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTotalMatches sets the "total_matches" field.
func (_u *UserStatsUpdateOne) SetTotalMatches(v int) *UserStatsUpdateOne {
	_u.mutation.ResetTotalMatches()
	_u.mutation.SetTotalMatches(v)
	return _u
}

// SetNillableTotalMatches sets the "total_matches" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableTotalMatches(v *int) *UserStatsUpdateOne {
	if v != nil {
		_u.SetTotalMatches(*v)
	}
	return _u
}

// AddTotalMatches adds value to the "total_matches" field.
func (_u *UserStatsUpdateOne) AddTotalMatches(v int) *UserStatsUpdateOne {
	_u.mutation.AddTotalMatches(v)
	return _u
}

// SetMatchesAttended sets the "matches_attended" field.
func (_u *UserStatsUpdateOne) SetMatchesAttended(v int) *UserStatsUpdateOne {
	_u.mutation.ResetMatchesAttended()
	_u.mutation.SetMatchesAttended(v)
	return _u
}

// SetNillableMatchesAttended sets the "matches_attended" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableMatchesAttended(v *int) *UserStatsUpdateOne {
	if v != nil {
		_u.SetMatchesAttended(*v)
	}
	return _u
}

// AddMatchesAttended adds value to the "matches_attended" field.
func (_u *UserStatsUpdateOne) AddMatchesAttended(v int) *UserStatsUpdateOne {
	_u.mutation.AddMatchesAttended(v)
	return _u
}

// SetMatchesOrganized sets the "matches_organized" field.
func (_u *UserStatsUpdateOne) SetMatchesOrganized(v int) *UserStatsUpdateOne {
	_u.mutation.ResetMatchesOrganized()
	_u.mutation.SetMatchesOrganized(v)
	return _u
}

// SetNillableMatchesOrganized sets the "matches_organized" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableMatchesOrganized(v *int) *UserStatsUpdateOne {
	if v != nil {
		_u.SetMatchesOrganized(*v)
	}
	return _u
}

// AddMatchesOrganized adds value to the "matches_organized" field.
func (_u *UserStatsUpdateOne) AddMatchesOrganized(v int) *UserStatsUpdateOne {
	_u.mutation.AddMatchesOrganized(v)
	return _u
}

// SetNoShows sets the "no_shows" field.
func (_u *UserStatsUpdateOne) SetNoShows(v int) *UserStatsUpdateOne {
	_u.mutation.ResetNoShows()
	_u.mutation.SetNoShows(v)
	return _u
}

// SetNillableNoShows sets the "no_shows" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableNoShows(v *int) *UserStatsUpdateOne {
	if v != nil {
		_u.SetNoShows(*v)
	}
	return _u
}

// AddNoShows adds value to the "no_shows" field.
func (_u *UserStatsUpdateOne) AddNoShows(v int) *UserStatsUpdateOne {
	_u.mutation.AddNoShows(v)
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *UserStatsUpdateOne) SetAverageRating(v float64) *UserStatsUpdateOne {
	_u.mutation.ResetAverageRating()
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableAverageRating(v *float64) *UserStatsUpdateOne {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// AddAverageRating adds value to the "average_rating" field.
func (_u *UserStatsUpdateOne) AddAverageRating(v float64) *UserStatsUpdateOne {
	_u.mutation.AddAverageRating(v)
	return _u
}

// SetTotalRatingsReceived sets the "total_ratings_received" field.
func (_u *UserStatsUpdateOne) SetTotalRatingsReceived(v int) *UserStatsUpdateOne {
	_u.mutation.ResetTotalRatingsReceived()
	_u.mutation.SetTotalRatingsReceived(v)
	return _u
}

// SetNillableTotalRatingsReceived sets the "total_ratings_received" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableTotalRatingsReceived(v *int) *UserStatsUpdateOne {
	if v != nil {
		_u.SetTotalRatingsReceived(*v)
	}
	return _u
}

// AddTotalRatingsReceived adds value to the "total_ratings_received" field.
func (_u *UserStatsUpdateOne) AddTotalRatingsReceived(v int) *UserStatsUpdateOne {
	_u.mutation.AddTotalRatingsReceived(v)
	return _u
}

// SetReliabilityScore sets the "reliability_score" field.
func (_u *UserStatsUpdateOne) SetReliabilityScore(v float64) *UserStatsUpdateOne {
	_u.mutation.ResetReliabilityScore()
	_u.mutation.SetReliabilityScore(v)
	return _u
}

// SetNillableReliabilityScore sets the "reliability_score" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableReliabilityScore(v *float64) *UserStatsUpdateOne {
	if v != nil {
		_u.SetReliabilityScore(*v)
	}
	return _u
}

// AddReliabilityScore adds value to the "reliability_score" field.
func (_u *UserStatsUpdateOne) AddReliabilityScore(v float64) *UserStatsUpdateOne {
	_u.mutation.AddReliabilityScore(v)
	return _u
}

// SetLastMatchAt sets the "last_match_at" field.
func (_u *UserStatsUpdateOne) SetLastMatchAt(v time.Time) *UserStatsUpdateOne {
	_u.mutation.SetLastMatchAt(v)
	return _u
}

// SetNillableLastMatchAt sets the "last_match_at" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableLastMatchAt(v *time.Time) *UserStatsUpdateOne {
	if v != nil {
		_u.SetLastMatchAt(*v)
	}
	return _u
}

// ClearLastMatchAt clears the value of the "last_match_at" field.
func (_u *UserStatsUpdateOne) ClearLastMatchAt() *UserStatsUpdateOne {
	_u.mutation.ClearLastMatchAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserStatsUpdateOne) SetUpdatedAt(v time.Time) *UserStatsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserStatsUpdateOne) SetUser(v *User) *UserStatsUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserStatsMutation object of the builder.
func (_u *UserStatsUpdateOne) Mutation() *UserStatsMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserStatsUpdateOne) ClearUser() *UserStatsUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserStatsUpdate builder.
func (_u *UserStatsUpdateOne) Where(ps ...predicate.UserStats) *UserStatsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserStatsUpdateOne) Select(field string, fields ...string) *UserStatsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserStats entity.
func (_u *UserStatsUpdateOne) Save(ctx context.Context) (*UserStats, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserStatsUpdateOne) SaveX(ctx context.Context) *UserStats {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserStatsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserStatsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserStatsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userstats.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserStatsUpdateOne) check() error {
	if v, ok := _u.mutation.AverageRating(); ok {
		if err := userstats.AverageRatingValidator(v); err != nil {
			return &ValidationError{Name: "average_rating", err: fmt.Errorf(`ent: validator failed for field "UserStats.average_rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReliabilityScore(); ok {
		if err := userstats.ReliabilityScoreValidator(v); err != nil {
			return &ValidationError{Name: "reliability_score", err: fmt.Errorf(`ent: validator failed for field "UserStats.reliability_score": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserStats.user"`)
	}
	return nil
}

func (_u *UserStatsUpdateOne) sqlSave(ctx context.Context) (_node *UserStats, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userstats.Table, userstats.Columns, sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserStats.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userstats.FieldID)
		for _, f := range fields {
			if !userstats.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userstats.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TotalMatches(); ok {
		_spec.SetField(userstats.FieldTotalMatches, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalMatches(); ok {
		_spec.AddField(userstats.FieldTotalMatches, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MatchesAttended(); ok {
		_spec.SetField(userstats.FieldMatchesAttended, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMatchesAttended(); ok {
		_spec.AddField(userstats.FieldMatchesAttended, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MatchesOrganized(); ok {
		_spec.SetField(userstats.FieldMatchesOrganized, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMatchesOrganized(); ok {
		_spec.AddField(userstats.FieldMatchesOrganized, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NoShows(); ok {
		_spec.SetField(userstats.FieldNoShows, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNoShows(); ok {
		_spec.AddField(userstats.FieldNoShows, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(userstats.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageRating(); ok {
		_spec.AddField(userstats.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRatingsReceived(); ok {
		_spec.SetField(userstats.FieldTotalRatingsReceived, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalRatingsReceived(); ok {
		_spec.AddField(userstats.FieldTotalRatingsReceived, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReliabilityScore(); ok {
		_spec.SetField(userstats.FieldReliabilityScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReliabilityScore(); ok {
		_spec.AddField(userstats.FieldReliabilityScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastMatchAt(); ok {
		_spec.SetField(userstats.FieldLastMatchAt, field.TypeTime, value)
	}
	if _u.mutation.LastMatchAtCleared() {
		_spec.ClearField(userstats.FieldLastMatchAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userstats.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userstats.UserTable,
			Columns: []string{userstats.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userstats.UserTable,
			Columns: []string{userstats.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserStats{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
