// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kicknroar/internal/ent/match"
	"kicknroar/internal/ent/matchparticipant"
	"kicknroar/internal/ent/notification"
	"kicknroar/internal/ent/predicate"
	"kicknroar/internal/ent/user"
	"kicknroar/internal/ent/userstats"
	"kicknroar/internal/ent/venue"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *UserUpdate) SetFullName(v string) *UserUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFullName(v *string) *UserUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdate) SetPhone(v string) *UserUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePhone(v *string) *UserUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetProfileImageURL sets the "profile_image_url" field.
func (_u *UserUpdate) SetProfileImageURL(v string) *UserUpdate {
	_u.mutation.SetProfileImageURL(v)
	return _u
}

// SetNillableProfileImageURL sets the "profile_image_url" field if the given value is not nil.
func (_u *UserUpdate) SetNillableProfileImageURL(v *string) *UserUpdate {
	if v != nil {
		_u.SetProfileImageURL(*v)
	}
	return _u
}

// ClearProfileImageURL clears the value of the "profile_image_url" field.
func (_u *UserUpdate) ClearProfileImageURL() *UserUpdate {
	_u.mutation.ClearProfileImageURL()
	return _u
}

// SetSkillLevel sets the "skill_level" field.
func (_u *UserUpdate) SetSkillLevel(v user.SkillLevel) *UserUpdate {
	_u.mutation.SetSkillLevel(v)
	return _u
}

// SetNillableSkillLevel sets the "skill_level" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSkillLevel(v *user.SkillLevel) *UserUpdate {
	if v != nil {
		_u.SetSkillLevel(*v)
	}
	return _u
}

// SetPreferredLocations sets the "preferred_locations" field.
func (_u *UserUpdate) SetPreferredLocations(v []string) *UserUpdate {
	_u.mutation.SetPreferredLocations(v)
	return _u
}

// AppendPreferredLocations appends value to the "preferred_locations" field.
func (_u *UserUpdate) AppendPreferredLocations(v []string) *UserUpdate {
	_u.mutation.AppendPreferredLocations(v)
	return _u
}

// ClearPreferredLocations clears the value of the "preferred_locations" field.
func (_u *UserUpdate) ClearPreferredLocations() *UserUpdate {
	_u.mutation.ClearPreferredLocations()
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *UserUpdate) SetIsVerified(v bool) *UserUpdate {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsVerified(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdate) SetIsActive(v bool) *UserUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsActive(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdate) SetLastLoginAt(v time.Time) *UserUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastLoginAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *UserUpdate) ClearLastLoginAt() *UserUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatsID sets the "stats" edge to the UserStats entity by ID.
func (_u *UserUpdate) SetStatsID(id int) *UserUpdate {
	_u.mutation.SetStatsID(id)
	return _u
}

// SetNillableStatsID sets the "stats" edge to the UserStats entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableStatsID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetStatsID(*id)
	}
	return _u
}

// SetStats sets the "stats" edge to the UserStats entity.
func (_u *UserUpdate) SetStats(v *UserStats) *UserUpdate {
	return _u.SetStatsID(v.ID)
}

// AddCreatedMatchIDs adds the "created_matches" edge to the Match entity by IDs.
func (_u *UserUpdate) AddCreatedMatchIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddCreatedMatchIDs(ids...)
	return _u
}

// AddCreatedMatches adds the "created_matches" edges to the Match entity.
func (_u *UserUpdate) AddCreatedMatches(v ...*Match) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedMatchIDs(ids...)
}

// AddParticipationIDs adds the "participations" edge to the MatchParticipant entity by IDs.
func (_u *UserUpdate) AddParticipationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddParticipationIDs(ids...)
	return _u
}

// AddParticipations adds the "participations" edges to the MatchParticipant entity.
func (_u *UserUpdate) AddParticipations(v ...*MatchParticipant) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipationIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *UserUpdate) AddNotificationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *UserUpdate) AddNotifications(v ...*Notification) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// AddOwnedVenueIDs adds the "owned_venues" edge to the Venue entity by IDs.
func (_u *UserUpdate) AddOwnedVenueIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddOwnedVenueIDs(ids...)
	return _u
}

// AddOwnedVenues adds the "owned_venues" edges to the Venue entity.
func (_u *UserUpdate) AddOwnedVenues(v ...*Venue) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnedVenueIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearStats clears the "stats" edge to the UserStats entity.
func (_u *UserUpdate) ClearStats() *UserUpdate {
	_u.mutation.ClearStats()
	return _u
}

// ClearCreatedMatches clears all "created_matches" edges to the Match entity.
func (_u *UserUpdate) ClearCreatedMatches() *UserUpdate {
	_u.mutation.ClearCreatedMatches()
	return _u
}

// RemoveCreatedMatchIDs removes the "created_matches" edge to Match entities by IDs.
func (_u *UserUpdate) RemoveCreatedMatchIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveCreatedMatchIDs(ids...)
	return _u
}

// RemoveCreatedMatches removes "created_matches" edges to Match entities.
func (_u *UserUpdate) RemoveCreatedMatches(v ...*Match) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedMatchIDs(ids...)
}

// ClearParticipations clears all "participations" edges to the MatchParticipant entity.
func (_u *UserUpdate) ClearParticipations() *UserUpdate {
	_u.mutation.ClearParticipations()
	return _u
}

// RemoveParticipationIDs removes the "participations" edge to MatchParticipant entities by IDs.
func (_u *UserUpdate) RemoveParticipationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveParticipationIDs(ids...)
	return _u
}

// RemoveParticipations removes "participations" edges to MatchParticipant entities.
func (_u *UserUpdate) RemoveParticipations(v ...*MatchParticipant) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipationIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *UserUpdate) ClearNotifications() *UserUpdate {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *UserUpdate) RemoveNotificationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *UserUpdate) RemoveNotifications(v ...*Notification) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// ClearOwnedVenues clears all "owned_venues" edges to the Venue entity.
func (_u *UserUpdate) ClearOwnedVenues() *UserUpdate {
	_u.mutation.ClearOwnedVenues()
	return _u
}

// RemoveOwnedVenueIDs removes the "owned_venues" edge to Venue entities by IDs.
func (_u *UserUpdate) RemoveOwnedVenueIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveOwnedVenueIDs(ids...)
	return _u
}

// RemoveOwnedVenues removes "owned_venues" edges to Venue entities.
func (_u *UserUpdate) RemoveOwnedVenues(v ...*Venue) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnedVenueIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := user.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "User.full_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := user.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "User.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProfileImageURL(); ok {
		if err := user.ProfileImageURLValidator(v); err != nil {
			return &ValidationError{Name: "profile_image_url", err: fmt.Errorf(`ent: validator failed for field "User.profile_image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkillLevel(); ok {
		if err := user.SkillLevelValidator(v); err != nil {
			return &ValidationError{Name: "skill_level", err: fmt.Errorf(`ent: validator failed for field "User.skill_level": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(user.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileImageURL(); ok {
		_spec.SetField(user.FieldProfileImageURL, field.TypeString, value)
	}
	if _u.mutation.ProfileImageURLCleared() {
		_spec.ClearField(user.FieldProfileImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.SkillLevel(); ok {
		_spec.SetField(user.FieldSkillLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PreferredLocations(); ok {
		_spec.SetField(user.FieldPreferredLocations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPreferredLocations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldPreferredLocations, value)
		})
	}
	if _u.mutation.PreferredLocationsCleared() {
		_spec.ClearField(user.FieldPreferredLocations, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(user.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(user.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.StatsTable,
			Columns: []string{user.StatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.StatsTable,
			Columns: []string{user.StatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedMatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreatedMatchesTable,
			Columns: []string{user.CreatedMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedMatchesIDs(); len(nodes) > 0 && !_u.mutation.CreatedMatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreatedMatchesTable,
			Columns: []string{user.CreatedMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedMatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreatedMatchesTable,
			Columns: []string{user.CreatedMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ParticipationsTable,
			Columns: []string{user.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipationsIDs(); len(nodes) > 0 && !_u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ParticipationsTable,
			Columns: []string{user.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ParticipationsTable,
			Columns: []string{user.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnedVenuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedVenuesTable,
			Columns: []string{user.OwnedVenuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnedVenuesIDs(); len(nodes) > 0 && !_u.mutation.OwnedVenuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedVenuesTable,
			Columns: []string{user.OwnedVenuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnedVenuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedVenuesTable,
			Columns: []string{user.OwnedVenuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *UserUpdateOne) SetFullName(v string) *UserUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFullName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdateOne) SetPhone(v string) *UserUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePhone(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetProfileImageURL sets the "profile_image_url" field.
func (_u *UserUpdateOne) SetProfileImageURL(v string) *UserUpdateOne {
	_u.mutation.SetProfileImageURL(v)
	return _u
}

// SetNillableProfileImageURL sets the "profile_image_url" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableProfileImageURL(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetProfileImageURL(*v)
	}
	return _u
}

// ClearProfileImageURL clears the value of the "profile_image_url" field.
func (_u *UserUpdateOne) ClearProfileImageURL() *UserUpdateOne {
	_u.mutation.ClearProfileImageURL()
	return _u
}

// SetSkillLevel sets the "skill_level" field.
func (_u *UserUpdateOne) SetSkillLevel(v user.SkillLevel) *UserUpdateOne {
	_u.mutation.SetSkillLevel(v)
	return _u
}

// SetNillableSkillLevel sets the "skill_level" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSkillLevel(v *user.SkillLevel) *UserUpdateOne {
	if v != nil {
		_u.SetSkillLevel(*v)
	}
	return _u
}

// SetPreferredLocations sets the "preferred_locations" field.
func (_u *UserUpdateOne) SetPreferredLocations(v []string) *UserUpdateOne {
	_u.mutation.SetPreferredLocations(v)
	return _u
}

// AppendPreferredLocations appends value to the "preferred_locations" field.
func (_u *UserUpdateOne) AppendPreferredLocations(v []string) *UserUpdateOne {
	_u.mutation.AppendPreferredLocations(v)
	return _u
}

// ClearPreferredLocations clears the value of the "preferred_locations" field.
func (_u *UserUpdateOne) ClearPreferredLocations() *UserUpdateOne {
	_u.mutation.ClearPreferredLocations()
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *UserUpdateOne) SetIsVerified(v bool) *UserUpdateOne {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsVerified(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdateOne) SetIsActive(v bool) *UserUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsActive(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdateOne) SetLastLoginAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastLoginAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *UserUpdateOne) ClearLastLoginAt() *UserUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatsID sets the "stats" edge to the UserStats entity by ID.
func (_u *UserUpdateOne) SetStatsID(id int) *UserUpdateOne {
	_u.mutation.SetStatsID(id)
	return _u
}

// SetNillableStatsID sets the "stats" edge to the UserStats entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableStatsID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetStatsID(*id)
	}
	return _u
}

// SetStats sets the "stats" edge to the UserStats entity.
func (_u *UserUpdateOne) SetStats(v *UserStats) *UserUpdateOne {
	return _u.SetStatsID(v.ID)
}

// AddCreatedMatchIDs adds the "created_matches" edge to the Match entity by IDs.
func (_u *UserUpdateOne) AddCreatedMatchIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddCreatedMatchIDs(ids...)
	return _u
}

// AddCreatedMatches adds the "created_matches" edges to the Match entity.
func (_u *UserUpdateOne) AddCreatedMatches(v ...*Match) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedMatchIDs(ids...)
}

// AddParticipationIDs adds the "participations" edge to the MatchParticipant entity by IDs.
func (_u *UserUpdateOne) AddParticipationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddParticipationIDs(ids...)
	return _u
}

// AddParticipations adds the "participations" edges to the MatchParticipant entity.
func (_u *UserUpdateOne) AddParticipations(v ...*MatchParticipant) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParticipationIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *UserUpdateOne) AddNotificationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *UserUpdateOne) AddNotifications(v ...*Notification) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// AddOwnedVenueIDs adds the "owned_venues" edge to the Venue entity by IDs.
func (_u *UserUpdateOne) AddOwnedVenueIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddOwnedVenueIDs(ids...)
	return _u
}

// AddOwnedVenues adds the "owned_venues" edges to the Venue entity.
func (_u *UserUpdateOne) AddOwnedVenues(v ...*Venue) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnedVenueIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearStats clears the "stats" edge to the UserStats entity.
func (_u *UserUpdateOne) ClearStats() *UserUpdateOne {
	_u.mutation.ClearStats()
	return _u
}

// ClearCreatedMatches clears all "created_matches" edges to the Match entity.
func (_u *UserUpdateOne) ClearCreatedMatches() *UserUpdateOne {
	_u.mutation.ClearCreatedMatches()
	return _u
}

// RemoveCreatedMatchIDs removes the "created_matches" edge to Match entities by IDs.
func (_u *UserUpdateOne) RemoveCreatedMatchIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveCreatedMatchIDs(ids...)
	return _u
}

// RemoveCreatedMatches removes "created_matches" edges to Match entities.
func (_u *UserUpdateOne) RemoveCreatedMatches(v ...*Match) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedMatchIDs(ids...)
}

// ClearParticipations clears all "participations" edges to the MatchParticipant entity.
func (_u *UserUpdateOne) ClearParticipations() *UserUpdateOne {
	_u.mutation.ClearParticipations()
	return _u
}

// RemoveParticipationIDs removes the "participations" edge to MatchParticipant entities by IDs.
func (_u *UserUpdateOne) RemoveParticipationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveParticipationIDs(ids...)
	return _u
}

// RemoveParticipations removes "participations" edges to MatchParticipant entities.
func (_u *UserUpdateOne) RemoveParticipations(v ...*MatchParticipant) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParticipationIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *UserUpdateOne) ClearNotifications() *UserUpdateOne {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *UserUpdateOne) RemoveNotificationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *UserUpdateOne) RemoveNotifications(v ...*Notification) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// ClearOwnedVenues clears all "owned_venues" edges to the Venue entity.
func (_u *UserUpdateOne) ClearOwnedVenues() *UserUpdateOne {
	_u.mutation.ClearOwnedVenues()
	return _u
}

// RemoveOwnedVenueIDs removes the "owned_venues" edge to Venue entities by IDs.
func (_u *UserUpdateOne) RemoveOwnedVenueIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveOwnedVenueIDs(ids...)
	return _u
}

// RemoveOwnedVenues removes "owned_venues" edges to Venue entities.
func (_u *UserUpdateOne) RemoveOwnedVenues(v ...*Venue) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnedVenueIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := user.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "User.full_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := user.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "User.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProfileImageURL(); ok {
		if err := user.ProfileImageURLValidator(v); err != nil {
			return &ValidationError{Name: "profile_image_url", err: fmt.Errorf(`ent: validator failed for field "User.profile_image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkillLevel(); ok {
		if err := user.SkillLevelValidator(v); err != nil {
			return &ValidationError{Name: "skill_level", err: fmt.Errorf(`ent: validator failed for field "User.skill_level": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(user.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileImageURL(); ok {
		_spec.SetField(user.FieldProfileImageURL, field.TypeString, value)
	}
	if _u.mutation.ProfileImageURLCleared() {
		_spec.ClearField(user.FieldProfileImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.SkillLevel(); ok {
		_spec.SetField(user.FieldSkillLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PreferredLocations(); ok {
		_spec.SetField(user.FieldPreferredLocations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPreferredLocations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldPreferredLocations, value)
		})
	}
	if _u.mutation.PreferredLocationsCleared() {
		_spec.ClearField(user.FieldPreferredLocations, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(user.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(user.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.StatsTable,
			Columns: []string{user.StatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.StatsTable,
			Columns: []string{user.StatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedMatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreatedMatchesTable,
			Columns: []string{user.CreatedMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedMatchesIDs(); len(nodes) > 0 && !_u.mutation.CreatedMatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreatedMatchesTable,
			Columns: []string{user.CreatedMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedMatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CreatedMatchesTable,
			Columns: []string{user.CreatedMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ParticipationsTable,
			Columns: []string{user.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParticipationsIDs(); len(nodes) > 0 && !_u.mutation.ParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ParticipationsTable,
			Columns: []string{user.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ParticipationsTable,
			Columns: []string{user.ParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(matchparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnedVenuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedVenuesTable,
			Columns: []string{user.OwnedVenuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnedVenuesIDs(); len(nodes) > 0 && !_u.mutation.OwnedVenuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedVenuesTable,
			Columns: []string{user.OwnedVenuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnedVenuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedVenuesTable,
			Columns: []string{user.OwnedVenuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
