// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kicknroar/internal/ent/match"
	"kicknroar/internal/ent/predicate"
	"kicknroar/internal/ent/user"
	"kicknroar/internal/ent/venue"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// VenueUpdate is the builder for updating Venue entities.
type VenueUpdate struct {
	config
	hooks    []Hook
	mutation *VenueMutation
}

// Where appends a list predicates to the VenueUpdate builder.
func (_u *VenueUpdate) Where(ps ...predicate.Venue) *VenueUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *VenueUpdate) SetName(v string) *VenueUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableName(v *string) *VenueUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *VenueUpdate) SetAddress(v string) *VenueUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableAddress(v *string) *VenueUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *VenueUpdate) SetLatitude(v float64) *VenueUpdate {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableLatitude(v *float64) *VenueUpdate {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *VenueUpdate) AddLatitude(v float64) *VenueUpdate {
	_u.mutation.AddLatitude(v)
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *VenueUpdate) SetLongitude(v float64) *VenueUpdate {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableLongitude(v *float64) *VenueUpdate {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *VenueUpdate) AddLongitude(v float64) *VenueUpdate {
	_u.mutation.AddLongitude(v)
	return _u
}

// SetGooglePlaceID sets the "google_place_id" field.
func (_u *VenueUpdate) SetGooglePlaceID(v string) *VenueUpdate {
	_u.mutation.SetGooglePlaceID(v)
	return _u
}

// SetNillableGooglePlaceID sets the "google_place_id" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableGooglePlaceID(v *string) *VenueUpdate {
	if v != nil {
		_u.SetGooglePlaceID(*v)
	}
	return _u
}

// ClearGooglePlaceID clears the value of the "google_place_id" field.
func (_u *VenueUpdate) ClearGooglePlaceID() *VenueUpdate {
	_u.mutation.ClearGooglePlaceID()
	return _u
}

// SetFieldType sets the "field_type" field.
func (_u *VenueUpdate) SetFieldType(v venue.FieldType) *VenueUpdate {
	_u.mutation.SetFieldType(v)
	return _u
}

// SetNillableFieldType sets the "field_type" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableFieldType(v *venue.FieldType) *VenueUpdate {
	if v != nil {
		_u.SetFieldType(*v)
	}
	return _u
}

// SetSurfaceType sets the "surface_type" field.
func (_u *VenueUpdate) SetSurfaceType(v venue.SurfaceType) *VenueUpdate {
	_u.mutation.SetSurfaceType(v)
	return _u
}

// SetNillableSurfaceType sets the "surface_type" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableSurfaceType(v *venue.SurfaceType) *VenueUpdate {
	if v != nil {
		_u.SetSurfaceType(*v)
	}
	return _u
}

// ClearSurfaceType clears the value of the "surface_type" field.
func (_u *VenueUpdate) ClearSurfaceType() *VenueUpdate {
	_u.mutation.ClearSurfaceType()
	return _u
}

// SetCapacity sets the "capacity" field.
func (_u *VenueUpdate) SetCapacity(v int) *VenueUpdate {
	_u.mutation.ResetCapacity()
	_u.mutation.SetCapacity(v)
	return _u
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableCapacity(v *int) *VenueUpdate {
	if v != nil {
		_u.SetCapacity(*v)
	}
	return _u
}

// AddCapacity adds value to the "capacity" field.
func (_u *VenueUpdate) AddCapacity(v int) *VenueUpdate {
	_u.mutation.AddCapacity(v)
	return _u
}

// SetHourlyRate sets the "hourly_rate" field.
func (_u *VenueUpdate) SetHourlyRate(v int) *VenueUpdate {
	_u.mutation.ResetHourlyRate()
	_u.mutation.SetHourlyRate(v)
	return _u
}

// SetNillableHourlyRate sets the "hourly_rate" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableHourlyRate(v *int) *VenueUpdate {
	if v != nil {
		_u.SetHourlyRate(*v)
	}
	return _u
}

// AddHourlyRate adds value to the "hourly_rate" field.
func (_u *VenueUpdate) AddHourlyRate(v int) *VenueUpdate {
	_u.mutation.AddHourlyRate(v)
	return _u
}

// ClearHourlyRate clears the value of the "hourly_rate" field.
func (_u *VenueUpdate) ClearHourlyRate() *VenueUpdate {
	_u.mutation.ClearHourlyRate()
	return _u
}

// SetFacilities sets the "facilities" field.
func (_u *VenueUpdate) SetFacilities(v []string) *VenueUpdate {
	_u.mutation.SetFacilities(v)
	return _u
}

// AppendFacilities appends value to the "facilities" field.
func (_u *VenueUpdate) AppendFacilities(v []string) *VenueUpdate {
	_u.mutation.AppendFacilities(v)
	return _u
}

// ClearFacilities clears the value of the "facilities" field.
func (_u *VenueUpdate) ClearFacilities() *VenueUpdate {
	_u.mutation.ClearFacilities()
	return _u
}

// SetImages sets the "images" field.
func (_u *VenueUpdate) SetImages(v []string) *VenueUpdate {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *VenueUpdate) AppendImages(v []string) *VenueUpdate {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *VenueUpdate) ClearImages() *VenueUpdate {
	_u.mutation.ClearImages()
	return _u
}

// SetContactInfo sets the "contact_info" field.
func (_u *VenueUpdate) SetContactInfo(v map[string]interface{}) *VenueUpdate {
	_u.mutation.SetContactInfo(v)
	return _u
}

// ClearContactInfo clears the value of the "contact_info" field.
func (_u *VenueUpdate) ClearContactInfo() *VenueUpdate {
	_u.mutation.ClearContactInfo()
	return _u
}

// SetOperatingHours sets the "operating_hours" field.
func (_u *VenueUpdate) SetOperatingHours(v map[string]interface{}) *VenueUpdate {
	_u.mutation.SetOperatingHours(v)
	return _u
}

// ClearOperatingHours clears the value of the "operating_hours" field.
func (_u *VenueUpdate) ClearOperatingHours() *VenueUpdate {
	_u.mutation.ClearOperatingHours()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *VenueUpdate) SetOwnerID(v uuid.UUID) *VenueUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableOwnerID(v *uuid.UUID) *VenueUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *VenueUpdate) ClearOwnerID() *VenueUpdate {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *VenueUpdate) SetIsVerified(v bool) *VenueUpdate {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableIsVerified(v *bool) *VenueUpdate {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *VenueUpdate) SetIsActive(v bool) *VenueUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableIsActive(v *bool) *VenueUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *VenueUpdate) SetRating(v float64) *VenueUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableRating(v *float64) *VenueUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *VenueUpdate) AddRating(v float64) *VenueUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetTotalRatings sets the "total_ratings" field.
func (_u *VenueUpdate) SetTotalRatings(v int) *VenueUpdate {
	_u.mutation.ResetTotalRatings()
	_u.mutation.SetTotalRatings(v)
	return _u
}

// SetNillableTotalRatings sets the "total_ratings" field if the given value is not nil.
func (_u *VenueUpdate) SetNillableTotalRatings(v *int) *VenueUpdate {
	if v != nil {
		_u.SetTotalRatings(*v)
	}
	return _u
}

// AddTotalRatings adds value to the "total_ratings" field.
func (_u *VenueUpdate) AddTotalRatings(v int) *VenueUpdate {
	_u.mutation.AddTotalRatings(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VenueUpdate) SetUpdatedAt(v time.Time) *VenueUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *VenueUpdate) SetOwner(v *User) *VenueUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddMatchIDs adds the "matches" edge to the Match entity by IDs.
func (_u *VenueUpdate) AddMatchIDs(ids ...uuid.UUID) *VenueUpdate {
	_u.mutation.AddMatchIDs(ids...)
	return _u
}

// AddMatches adds the "matches" edges to the Match entity.
func (_u *VenueUpdate) AddMatches(v ...*Match) *VenueUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMatchIDs(ids...)
}

// Mutation returns the VenueMutation object of the builder.
func (_u *VenueUpdate) Mutation() *VenueMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *VenueUpdate) ClearOwner() *VenueUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMatches clears all "matches" edges to the Match entity.
func (_u *VenueUpdate) ClearMatches() *VenueUpdate {
	_u.mutation.ClearMatches()
	return _u
}

// RemoveMatchIDs removes the "matches" edge to Match entities by IDs.
func (_u *VenueUpdate) RemoveMatchIDs(ids ...uuid.UUID) *VenueUpdate {
	_u.mutation.RemoveMatchIDs(ids...)
	return _u
}

// RemoveMatches removes "matches" edges to Match entities.
func (_u *VenueUpdate) RemoveMatches(v ...*Match) *VenueUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMatchIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VenueUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VenueUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VenueUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VenueUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VenueUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := venue.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VenueUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := venue.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Venue.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := venue.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Venue.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GooglePlaceID(); ok {
		if err := venue.GooglePlaceIDValidator(v); err != nil {
			return &ValidationError{Name: "google_place_id", err: fmt.Errorf(`ent: validator failed for field "Venue.google_place_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldType(); ok {
		if err := venue.FieldTypeValidator(v); err != nil {
			return &ValidationError{Name: "field_type", err: fmt.Errorf(`ent: validator failed for field "Venue.field_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SurfaceType(); ok {
		if err := venue.SurfaceTypeValidator(v); err != nil {
			return &ValidationError{Name: "surface_type", err: fmt.Errorf(`ent: validator failed for field "Venue.surface_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Capacity(); ok {
		if err := venue.CapacityValidator(v); err != nil {
			return &ValidationError{Name: "capacity", err: fmt.Errorf(`ent: validator failed for field "Venue.capacity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := venue.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Venue.rating": %w`, err)}
		}
	}
	return nil
}

func (_u *VenueUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(venue.Table, venue.Columns, sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(venue.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(venue.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(venue.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(venue.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(venue.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(venue.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GooglePlaceID(); ok {
		_spec.SetField(venue.FieldGooglePlaceID, field.TypeString, value)
	}
	if _u.mutation.GooglePlaceIDCleared() {
		_spec.ClearField(venue.FieldGooglePlaceID, field.TypeString)
	}
	if value, ok := _u.mutation.FieldType(); ok {
		_spec.SetField(venue.FieldFieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SurfaceType(); ok {
		_spec.SetField(venue.FieldSurfaceType, field.TypeEnum, value)
	}
	if _u.mutation.SurfaceTypeCleared() {
		_spec.ClearField(venue.FieldSurfaceType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Capacity(); ok {
		_spec.SetField(venue.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacity(); ok {
		_spec.AddField(venue.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HourlyRate(); ok {
		_spec.SetField(venue.FieldHourlyRate, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHourlyRate(); ok {
		_spec.AddField(venue.FieldHourlyRate, field.TypeInt, value)
	}
	if _u.mutation.HourlyRateCleared() {
		_spec.ClearField(venue.FieldHourlyRate, field.TypeInt)
	}
	if value, ok := _u.mutation.Facilities(); ok {
		_spec.SetField(venue.FieldFacilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFacilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, venue.FieldFacilities, value)
		})
	}
	if _u.mutation.FacilitiesCleared() {
		_spec.ClearField(venue.FieldFacilities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(venue.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, venue.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(venue.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContactInfo(); ok {
		_spec.SetField(venue.FieldContactInfo, field.TypeJSON, value)
	}
	if _u.mutation.ContactInfoCleared() {
		_spec.ClearField(venue.FieldContactInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.OperatingHours(); ok {
		_spec.SetField(venue.FieldOperatingHours, field.TypeJSON, value)
	}
	if _u.mutation.OperatingHoursCleared() {
		_spec.ClearField(venue.FieldOperatingHours, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(venue.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(venue.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(venue.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(venue.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRatings(); ok {
		_spec.SetField(venue.FieldTotalRatings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalRatings(); ok {
		_spec.AddField(venue.FieldTotalRatings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(venue.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   venue.OwnerTable,
			Columns: []string{venue.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   venue.OwnerTable,
			Columns: []string{venue.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   venue.MatchesTable,
			Columns: []string{venue.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMatchesIDs(); len(nodes) > 0 && !_u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   venue.MatchesTable,
			Columns: []string{venue.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   venue.MatchesTable,
			Columns: []string{venue.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{venue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VenueUpdateOne is the builder for updating a single Venue entity.
type VenueUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VenueMutation
}

// SetName sets the "name" field.
func (_u *VenueUpdateOne) SetName(v string) *VenueUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableName(v *string) *VenueUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *VenueUpdateOne) SetAddress(v string) *VenueUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableAddress(v *string) *VenueUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *VenueUpdateOne) SetLatitude(v float64) *VenueUpdateOne {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableLatitude(v *float64) *VenueUpdateOne {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *VenueUpdateOne) AddLatitude(v float64) *VenueUpdateOne {
	_u.mutation.AddLatitude(v)
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *VenueUpdateOne) SetLongitude(v float64) *VenueUpdateOne {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableLongitude(v *float64) *VenueUpdateOne {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *VenueUpdateOne) AddLongitude(v float64) *VenueUpdateOne {
	_u.mutation.AddLongitude(v)
	return _u
}

// SetGooglePlaceID sets the "google_place_id" field.
func (_u *VenueUpdateOne) SetGooglePlaceID(v string) *VenueUpdateOne {
	_u.mutation.SetGooglePlaceID(v)
	return _u
}

// SetNillableGooglePlaceID sets the "google_place_id" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableGooglePlaceID(v *string) *VenueUpdateOne {
	if v != nil {
		_u.SetGooglePlaceID(*v)
	}
	return _u
}

// ClearGooglePlaceID clears the value of the "google_place_id" field.
func (_u *VenueUpdateOne) ClearGooglePlaceID() *VenueUpdateOne {
	_u.mutation.ClearGooglePlaceID()
	return _u
}

// SetFieldType sets the "field_type" field.
func (_u *VenueUpdateOne) SetFieldType(v venue.FieldType) *VenueUpdateOne {
	_u.mutation.SetFieldType(v)
	return _u
}

// SetNillableFieldType sets the "field_type" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableFieldType(v *venue.FieldType) *VenueUpdateOne {
	if v != nil {
		_u.SetFieldType(*v)
	}
	return _u
}

// SetSurfaceType sets the "surface_type" field.
func (_u *VenueUpdateOne) SetSurfaceType(v venue.SurfaceType) *VenueUpdateOne {
	_u.mutation.SetSurfaceType(v)
	return _u
}

// SetNillableSurfaceType sets the "surface_type" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableSurfaceType(v *venue.SurfaceType) *VenueUpdateOne {
	if v != nil {
		_u.SetSurfaceType(*v)
	}
	return _u
}

// ClearSurfaceType clears the value of the "surface_type" field.
func (_u *VenueUpdateOne) ClearSurfaceType() *VenueUpdateOne {
	_u.mutation.ClearSurfaceType()
	return _u
}

// SetCapacity sets the "capacity" field.
func (_u *VenueUpdateOne) SetCapacity(v int) *VenueUpdateOne {
	_u.mutation.ResetCapacity()
	_u.mutation.SetCapacity(v)
	return _u
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableCapacity(v *int) *VenueUpdateOne {
	if v != nil {
		_u.SetCapacity(*v)
	}
	return _u
}

// AddCapacity adds value to the "capacity" field.
func (_u *VenueUpdateOne) AddCapacity(v int) *VenueUpdateOne {
	_u.mutation.AddCapacity(v)
	return _u
}

// SetHourlyRate sets the "hourly_rate" field.
func (_u *VenueUpdateOne) SetHourlyRate(v int) *VenueUpdateOne {
	_u.mutation.ResetHourlyRate()
	_u.mutation.SetHourlyRate(v)
	return _u
}

// SetNillableHourlyRate sets the "hourly_rate" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableHourlyRate(v *int) *VenueUpdateOne {
	if v != nil {
		_u.SetHourlyRate(*v)
	}
	return _u
}

// AddHourlyRate adds value to the "hourly_rate" field.
func (_u *VenueUpdateOne) AddHourlyRate(v int) *VenueUpdateOne {
	_u.mutation.AddHourlyRate(v)
	return _u
}

// ClearHourlyRate clears the value of the "hourly_rate" field.
func (_u *VenueUpdateOne) ClearHourlyRate() *VenueUpdateOne {
	_u.mutation.ClearHourlyRate()
	return _u
}

// SetFacilities sets the "facilities" field.
func (_u *VenueUpdateOne) SetFacilities(v []string) *VenueUpdateOne {
	_u.mutation.SetFacilities(v)
	return _u
}

// AppendFacilities appends value to the "facilities" field.
func (_u *VenueUpdateOne) AppendFacilities(v []string) *VenueUpdateOne {
	_u.mutation.AppendFacilities(v)
	return _u
}

// ClearFacilities clears the value of the "facilities" field.
func (_u *VenueUpdateOne) ClearFacilities() *VenueUpdateOne {
	_u.mutation.ClearFacilities()
	return _u
}

// SetImages sets the "images" field.
func (_u *VenueUpdateOne) SetImages(v []string) *VenueUpdateOne {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *VenueUpdateOne) AppendImages(v []string) *VenueUpdateOne {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *VenueUpdateOne) ClearImages() *VenueUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// SetContactInfo sets the "contact_info" field.
func (_u *VenueUpdateOne) SetContactInfo(v map[string]interface{}) *VenueUpdateOne {
	_u.mutation.SetContactInfo(v)
	return _u
}

// ClearContactInfo clears the value of the "contact_info" field.
func (_u *VenueUpdateOne) ClearContactInfo() *VenueUpdateOne {
	_u.mutation.ClearContactInfo()
	return _u
}

// SetOperatingHours sets the "operating_hours" field.
func (_u *VenueUpdateOne) SetOperatingHours(v map[string]interface{}) *VenueUpdateOne {
	_u.mutation.SetOperatingHours(v)
	return _u
}

// ClearOperatingHours clears the value of the "operating_hours" field.
func (_u *VenueUpdateOne) ClearOperatingHours() *VenueUpdateOne {
	_u.mutation.ClearOperatingHours()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *VenueUpdateOne) SetOwnerID(v uuid.UUID) *VenueUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableOwnerID(v *uuid.UUID) *VenueUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *VenueUpdateOne) ClearOwnerID() *VenueUpdateOne {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *VenueUpdateOne) SetIsVerified(v bool) *VenueUpdateOne {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableIsVerified(v *bool) *VenueUpdateOne {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *VenueUpdateOne) SetIsActive(v bool) *VenueUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableIsActive(v *bool) *VenueUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *VenueUpdateOne) SetRating(v float64) *VenueUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableRating(v *float64) *VenueUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *VenueUpdateOne) AddRating(v float64) *VenueUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetTotalRatings sets the "total_ratings" field.
func (_u *VenueUpdateOne) SetTotalRatings(v int) *VenueUpdateOne {
	_u.mutation.ResetTotalRatings()
	_u.mutation.SetTotalRatings(v)
	return _u
}

// SetNillableTotalRatings sets the "total_ratings" field if the given value is not nil.
func (_u *VenueUpdateOne) SetNillableTotalRatings(v *int) *VenueUpdateOne {
	if v != nil {
		_u.SetTotalRatings(*v)
	}
	return _u
}

// AddTotalRatings adds value to the "total_ratings" field.
func (_u *VenueUpdateOne) AddTotalRatings(v int) *VenueUpdateOne {
	_u.mutation.AddTotalRatings(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VenueUpdateOne) SetUpdatedAt(v time.Time) *VenueUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *VenueUpdateOne) SetOwner(v *User) *VenueUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddMatchIDs adds the "matches" edge to the Match entity by IDs.
func (_u *VenueUpdateOne) AddMatchIDs(ids ...uuid.UUID) *VenueUpdateOne {
	_u.mutation.AddMatchIDs(ids...)
	return _u
}

// AddMatches adds the "matches" edges to the Match entity.
func (_u *VenueUpdateOne) AddMatches(v ...*Match) *VenueUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMatchIDs(ids...)
}

// Mutation returns the VenueMutation object of the builder.
func (_u *VenueUpdateOne) Mutation() *VenueMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *VenueUpdateOne) ClearOwner() *VenueUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMatches clears all "matches" edges to the Match entity.
func (_u *VenueUpdateOne) ClearMatches() *VenueUpdateOne {
	_u.mutation.ClearMatches()
	return _u
}

// RemoveMatchIDs removes the "matches" edge to Match entities by IDs.
func (_u *VenueUpdateOne) RemoveMatchIDs(ids ...uuid.UUID) *VenueUpdateOne {
	_u.mutation.RemoveMatchIDs(ids...)
	return _u
}

// RemoveMatches removes "matches" edges to Match entities.
func (_u *VenueUpdateOne) RemoveMatches(v ...*Match) *VenueUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMatchIDs(ids...)
}

// Where appends a list predicates to the VenueUpdate builder.
func (_u *VenueUpdateOne) Where(ps ...predicate.Venue) *VenueUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VenueUpdateOne) Select(field string, fields ...string) *VenueUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Venue entity.
func (_u *VenueUpdateOne) Save(ctx context.Context) (*Venue, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VenueUpdateOne) SaveX(ctx context.Context) *Venue {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VenueUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VenueUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VenueUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := venue.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VenueUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := venue.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Venue.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := venue.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Venue.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GooglePlaceID(); ok {
		if err := venue.GooglePlaceIDValidator(v); err != nil {
			return &ValidationError{Name: "google_place_id", err: fmt.Errorf(`ent: validator failed for field "Venue.google_place_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldType(); ok {
		if err := venue.FieldTypeValidator(v); err != nil {
			return &ValidationError{Name: "field_type", err: fmt.Errorf(`ent: validator failed for field "Venue.field_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SurfaceType(); ok {
		if err := venue.SurfaceTypeValidator(v); err != nil {
			return &ValidationError{Name: "surface_type", err: fmt.Errorf(`ent: validator failed for field "Venue.surface_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Capacity(); ok {
		if err := venue.CapacityValidator(v); err != nil {
			return &ValidationError{Name: "capacity", err: fmt.Errorf(`ent: validator failed for field "Venue.capacity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := venue.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Venue.rating": %w`, err)}
		}
	}
	return nil
}

func (_u *VenueUpdateOne) sqlSave(ctx context.Context) (_node *Venue, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(venue.Table, venue.Columns, sqlgraph.NewFieldSpec(venue.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Venue.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, venue.FieldID)
		for _, f := range fields {
			if !venue.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != venue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(venue.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(venue.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(venue.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(venue.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(venue.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(venue.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GooglePlaceID(); ok {
		_spec.SetField(venue.FieldGooglePlaceID, field.TypeString, value)
	}
	if _u.mutation.GooglePlaceIDCleared() {
		_spec.ClearField(venue.FieldGooglePlaceID, field.TypeString)
	}
	if value, ok := _u.mutation.FieldType(); ok {
		_spec.SetField(venue.FieldFieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SurfaceType(); ok {
		_spec.SetField(venue.FieldSurfaceType, field.TypeEnum, value)
	}
	if _u.mutation.SurfaceTypeCleared() {
		_spec.ClearField(venue.FieldSurfaceType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Capacity(); ok {
		_spec.SetField(venue.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacity(); ok {
		_spec.AddField(venue.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HourlyRate(); ok {
		_spec.SetField(venue.FieldHourlyRate, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHourlyRate(); ok {
		_spec.AddField(venue.FieldHourlyRate, field.TypeInt, value)
	}
	if _u.mutation.HourlyRateCleared() {
		_spec.ClearField(venue.FieldHourlyRate, field.TypeInt)
	}
	if value, ok := _u.mutation.Facilities(); ok {
		_spec.SetField(venue.FieldFacilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFacilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, venue.FieldFacilities, value)
		})
	}
	if _u.mutation.FacilitiesCleared() {
		_spec.ClearField(venue.FieldFacilities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(venue.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, venue.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(venue.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContactInfo(); ok {
		_spec.SetField(venue.FieldContactInfo, field.TypeJSON, value)
	}
	if _u.mutation.ContactInfoCleared() {
		_spec.ClearField(venue.FieldContactInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.OperatingHours(); ok {
		_spec.SetField(venue.FieldOperatingHours, field.TypeJSON, value)
	}
	if _u.mutation.OperatingHoursCleared() {
		_spec.ClearField(venue.FieldOperatingHours, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(venue.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(venue.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(venue.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(venue.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRatings(); ok {
		_spec.SetField(venue.FieldTotalRatings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalRatings(); ok {
		_spec.AddField(venue.FieldTotalRatings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(venue.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   venue.OwnerTable,
			Columns: []string{venue.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   venue.OwnerTable,
			Columns: []string{venue.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   venue.MatchesTable,
			Columns: []string{venue.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMatchesIDs(); len(nodes) > 0 && !_u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   venue.MatchesTable,
			Columns: []string{venue.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   venue.MatchesTable,
			Columns: []string{venue.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Venue{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{venue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
