// Code generated by ent, DO NOT EDIT.

package userstats

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userstats type in the database.
	Label = "user_stats"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTotalMatches holds the string denoting the total_matches field in the database.
	FieldTotalMatches = "total_matches"
	// FieldMatchesAttended holds the string denoting the matches_attended field in the database.
	FieldMatchesAttended = "matches_attended"
	// FieldMatchesOrganized holds the string denoting the matches_organized field in the database.
	FieldMatchesOrganized = "matches_organized"
	// FieldNoShows holds the string denoting the no_shows field in the database.
	FieldNoShows = "no_shows"
	// FieldAverageRating holds the string denoting the average_rating field in the database.
	FieldAverageRating = "average_rating"
	// FieldTotalRatingsReceived holds the string denoting the total_ratings_received field in the database.
	FieldTotalRatingsReceived = "total_ratings_received"
	// FieldReliabilityScore holds the string denoting the reliability_score field in the database.
	FieldReliabilityScore = "reliability_score"
	// FieldLastMatchAt holds the string denoting the last_match_at field in the database.
	FieldLastMatchAt = "last_match_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userstats in the database.
	Table = "user_stats"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_stats"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userstats fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldTotalMatches,
	FieldMatchesAttended,
	FieldMatchesOrganized,
	FieldNoShows,
	FieldAverageRating,
	FieldTotalRatingsReceived,
	FieldReliabilityScore,
	FieldLastMatchAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTotalMatches holds the default value on creation for the "total_matches" field.
	DefaultTotalMatches int
	// DefaultMatchesAttended holds the default value on creation for the "matches_attended" field.
	DefaultMatchesAttended int
	// DefaultMatchesOrganized holds the default value on creation for the "matches_organized" field.
	DefaultMatchesOrganized int
	// DefaultNoShows holds the default value on creation for the "no_shows" field.
	DefaultNoShows int
	// DefaultAverageRating holds the default value on creation for the "average_rating" field.
	DefaultAverageRating float64
	// AverageRatingValidator is a validator for the "average_rating" field. It is called by the builders before save.
	AverageRatingValidator func(float64) error
	// DefaultTotalRatingsReceived holds the default value on creation for the "total_ratings_received" field.
	DefaultTotalRatingsReceived int
	// DefaultReliabilityScore holds the default value on creation for the "reliability_score" field.
	DefaultReliabilityScore float64
	// ReliabilityScoreValidator is a validator for the "reliability_score" field. It is called by the builders before save.
	ReliabilityScoreValidator func(float64) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserStats queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTotalMatches orders the results by the total_matches field.
func ByTotalMatches(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalMatches, opts...).ToFunc()
}

// ByMatchesAttended orders the results by the matches_attended field.
func ByMatchesAttended(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchesAttended, opts...).ToFunc()
}

// ByMatchesOrganized orders the results by the matches_organized field.
func ByMatchesOrganized(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchesOrganized, opts...).ToFunc()
}

// ByNoShows orders the results by the no_shows field.
func ByNoShows(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoShows, opts...).ToFunc()
}

// ByAverageRating orders the results by the average_rating field.
func ByAverageRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAverageRating, opts...).ToFunc()
}

// ByTotalRatingsReceived orders the results by the total_ratings_received field.
func ByTotalRatingsReceived(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRatingsReceived, opts...).ToFunc()
}

// ByReliabilityScore orders the results by the reliability_score field.
func ByReliabilityScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReliabilityScore, opts...).ToFunc()
}

// ByLastMatchAt orders the results by the last_match_at field.
func ByLastMatchAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMatchAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
