// Code generated by ent, DO NOT EDIT.

package userstats

import (
	"kicknroar/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldUserID, v))
}

// TotalMatches applies equality check predicate on the "total_matches" field. It's identical to TotalMatchesEQ.
func TotalMatches(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldTotalMatches, v))
}

// MatchesAttended applies equality check predicate on the "matches_attended" field. It's identical to MatchesAttendedEQ.
func MatchesAttended(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldMatchesAttended, v))
}

// MatchesOrganized applies equality check predicate on the "matches_organized" field. It's identical to MatchesOrganizedEQ.
func MatchesOrganized(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldMatchesOrganized, v))
}

// NoShows applies equality check predicate on the "no_shows" field. It's identical to NoShowsEQ.
func NoShows(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldNoShows, v))
}

// AverageRating applies equality check predicate on the "average_rating" field. It's identical to AverageRatingEQ.
func AverageRating(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldAverageRating, v))
}

// TotalRatingsReceived applies equality check predicate on the "total_ratings_received" field. It's identical to TotalRatingsReceivedEQ.
func TotalRatingsReceived(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldTotalRatingsReceived, v))
}

// ReliabilityScore applies equality check predicate on the "reliability_score" field. It's identical to ReliabilityScoreEQ.
func ReliabilityScore(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldReliabilityScore, v))
}

// LastMatchAt applies equality check predicate on the "last_match_at" field. It's identical to LastMatchAtEQ.
func LastMatchAt(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldLastMatchAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldUserID, vs...))
}

// TotalMatchesEQ applies the EQ predicate on the "total_matches" field.
func TotalMatchesEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldTotalMatches, v))
}

// TotalMatchesNEQ applies the NEQ predicate on the "total_matches" field.
func TotalMatchesNEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldTotalMatches, v))
}

// TotalMatchesIn applies the In predicate on the "total_matches" field.
func TotalMatchesIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldTotalMatches, vs...))
}

// TotalMatchesNotIn applies the NotIn predicate on the "total_matches" field.
func TotalMatchesNotIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldTotalMatches, vs...))
}

// TotalMatchesGT applies the GT predicate on the "total_matches" field.
func TotalMatchesGT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldTotalMatches, v))
}

// TotalMatchesGTE applies the GTE predicate on the "total_matches" field.
func TotalMatchesGTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldTotalMatches, v))
}

// TotalMatchesLT applies the LT predicate on the "total_matches" field.
func TotalMatchesLT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldTotalMatches, v))
}

// TotalMatchesLTE applies the LTE predicate on the "total_matches" field.
func TotalMatchesLTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldTotalMatches, v))
}

// MatchesAttendedEQ applies the EQ predicate on the "matches_attended" field.
func MatchesAttendedEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldMatchesAttended, v))
}

// MatchesAttendedNEQ applies the NEQ predicate on the "matches_attended" field.
func MatchesAttendedNEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldMatchesAttended, v))
}

// MatchesAttendedIn applies the In predicate on the "matches_attended" field.
func MatchesAttendedIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldMatchesAttended, vs...))
}

// MatchesAttendedNotIn applies the NotIn predicate on the "matches_attended" field.
func MatchesAttendedNotIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldMatchesAttended, vs...))
}

// MatchesAttendedGT applies the GT predicate on the "matches_attended" field.
func MatchesAttendedGT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldMatchesAttended, v))
}

// MatchesAttendedGTE applies the GTE predicate on the "matches_attended" field.
func MatchesAttendedGTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldMatchesAttended, v))
}

// MatchesAttendedLT applies the LT predicate on the "matches_attended" field.
func MatchesAttendedLT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldMatchesAttended, v))
}

// MatchesAttendedLTE applies the LTE predicate on the "matches_attended" field.
func MatchesAttendedLTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldMatchesAttended, v))
}

// MatchesOrganizedEQ applies the EQ predicate on the "matches_organized" field.
func MatchesOrganizedEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldMatchesOrganized, v))
}

// MatchesOrganizedNEQ applies the NEQ predicate on the "matches_organized" field.
func MatchesOrganizedNEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldMatchesOrganized, v))
}

// MatchesOrganizedIn applies the In predicate on the "matches_organized" field.
func MatchesOrganizedIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldMatchesOrganized, vs...))
}

// MatchesOrganizedNotIn applies the NotIn predicate on the "matches_organized" field.
func MatchesOrganizedNotIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldMatchesOrganized, vs...))
}

// MatchesOrganizedGT applies the GT predicate on the "matches_organized" field.
func MatchesOrganizedGT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldMatchesOrganized, v))
}

// MatchesOrganizedGTE applies the GTE predicate on the "matches_organized" field.
func MatchesOrganizedGTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldMatchesOrganized, v))
}

// MatchesOrganizedLT applies the LT predicate on the "matches_organized" field.
func MatchesOrganizedLT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldMatchesOrganized, v))
}

// MatchesOrganizedLTE applies the LTE predicate on the "matches_organized" field.
func MatchesOrganizedLTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldMatchesOrganized, v))
}

// NoShowsEQ applies the EQ predicate on the "no_shows" field.
func NoShowsEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldNoShows, v))
}

// NoShowsNEQ applies the NEQ predicate on the "no_shows" field.
func NoShowsNEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldNoShows, v))
}

// NoShowsIn applies the In predicate on the "no_shows" field.
func NoShowsIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldNoShows, vs...))
}

// NoShowsNotIn applies the NotIn predicate on the "no_shows" field.
func NoShowsNotIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldNoShows, vs...))
}

// NoShowsGT applies the GT predicate on the "no_shows" field.
func NoShowsGT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldNoShows, v))
}

// NoShowsGTE applies the GTE predicate on the "no_shows" field.
func NoShowsGTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldNoShows, v))
}

// NoShowsLT applies the LT predicate on the "no_shows" field.
func NoShowsLT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldNoShows, v))
}

// NoShowsLTE applies the LTE predicate on the "no_shows" field.
func NoShowsLTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldNoShows, v))
}

// AverageRatingEQ applies the EQ predicate on the "average_rating" field.
func AverageRatingEQ(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldAverageRating, v))
}

// AverageRatingNEQ applies the NEQ predicate on the "average_rating" field.
func AverageRatingNEQ(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldAverageRating, v))
}

// AverageRatingIn applies the In predicate on the "average_rating" field.
func AverageRatingIn(vs ...float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldAverageRating, vs...))
}

// AverageRatingNotIn applies the NotIn predicate on the "average_rating" field.
func AverageRatingNotIn(vs ...float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldAverageRating, vs...))
}

// AverageRatingGT applies the GT predicate on the "average_rating" field.
func AverageRatingGT(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldAverageRating, v))
}

// AverageRatingGTE applies the GTE predicate on the "average_rating" field.
func AverageRatingGTE(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldAverageRating, v))
}

// AverageRatingLT applies the LT predicate on the "average_rating" field.
func AverageRatingLT(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldAverageRating, v))
}

// AverageRatingLTE applies the LTE predicate on the "average_rating" field.
func AverageRatingLTE(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldAverageRating, v))
}

// TotalRatingsReceivedEQ applies the EQ predicate on the "total_ratings_received" field.
func TotalRatingsReceivedEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldTotalRatingsReceived, v))
}

// TotalRatingsReceivedNEQ applies the NEQ predicate on the "total_ratings_received" field.
func TotalRatingsReceivedNEQ(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldTotalRatingsReceived, v))
}

// TotalRatingsReceivedIn applies the In predicate on the "total_ratings_received" field.
func TotalRatingsReceivedIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldTotalRatingsReceived, vs...))
}

// TotalRatingsReceivedNotIn applies the NotIn predicate on the "total_ratings_received" field.
func TotalRatingsReceivedNotIn(vs ...int) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldTotalRatingsReceived, vs...))
}

// TotalRatingsReceivedGT applies the GT predicate on the "total_ratings_received" field.
func TotalRatingsReceivedGT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldTotalRatingsReceived, v))
}

// TotalRatingsReceivedGTE applies the GTE predicate on the "total_ratings_received" field.
func TotalRatingsReceivedGTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldTotalRatingsReceived, v))
}

// TotalRatingsReceivedLT applies the LT predicate on the "total_ratings_received" field.
func TotalRatingsReceivedLT(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldTotalRatingsReceived, v))
}

// TotalRatingsReceivedLTE applies the LTE predicate on the "total_ratings_received" field.
func TotalRatingsReceivedLTE(v int) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldTotalRatingsReceived, v))
}

// ReliabilityScoreEQ applies the EQ predicate on the "reliability_score" field.
func ReliabilityScoreEQ(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldReliabilityScore, v))
}

// ReliabilityScoreNEQ applies the NEQ predicate on the "reliability_score" field.
func ReliabilityScoreNEQ(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldReliabilityScore, v))
}

// ReliabilityScoreIn applies the In predicate on the "reliability_score" field.
func ReliabilityScoreIn(vs ...float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldReliabilityScore, vs...))
}

// ReliabilityScoreNotIn applies the NotIn predicate on the "reliability_score" field.
func ReliabilityScoreNotIn(vs ...float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldReliabilityScore, vs...))
}

// ReliabilityScoreGT applies the GT predicate on the "reliability_score" field.
func ReliabilityScoreGT(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldReliabilityScore, v))
}

// ReliabilityScoreGTE applies the GTE predicate on the "reliability_score" field.
func ReliabilityScoreGTE(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldReliabilityScore, v))
}

// ReliabilityScoreLT applies the LT predicate on the "reliability_score" field.
func ReliabilityScoreLT(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldReliabilityScore, v))
}

// ReliabilityScoreLTE applies the LTE predicate on the "reliability_score" field.
func ReliabilityScoreLTE(v float64) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldReliabilityScore, v))
}

// LastMatchAtEQ applies the EQ predicate on the "last_match_at" field.
func LastMatchAtEQ(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldLastMatchAt, v))
}

// LastMatchAtNEQ applies the NEQ predicate on the "last_match_at" field.
func LastMatchAtNEQ(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldLastMatchAt, v))
}

// LastMatchAtIn applies the In predicate on the "last_match_at" field.
func LastMatchAtIn(vs ...time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldLastMatchAt, vs...))
}

// LastMatchAtNotIn applies the NotIn predicate on the "last_match_at" field.
func LastMatchAtNotIn(vs ...time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldLastMatchAt, vs...))
}

// LastMatchAtGT applies the GT predicate on the "last_match_at" field.
func LastMatchAtGT(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldLastMatchAt, v))
}

// LastMatchAtGTE applies the GTE predicate on the "last_match_at" field.
func LastMatchAtGTE(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldLastMatchAt, v))
}

// LastMatchAtLT applies the LT predicate on the "last_match_at" field.
func LastMatchAtLT(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldLastMatchAt, v))
}

// LastMatchAtLTE applies the LTE predicate on the "last_match_at" field.
func LastMatchAtLTE(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldLastMatchAt, v))
}

// LastMatchAtIsNil applies the IsNil predicate on the "last_match_at" field.
func LastMatchAtIsNil() predicate.UserStats {
	return predicate.UserStats(sql.FieldIsNull(FieldLastMatchAt))
}

// LastMatchAtNotNil applies the NotNil predicate on the "last_match_at" field.
func LastMatchAtNotNil() predicate.UserStats {
	return predicate.UserStats(sql.FieldNotNull(FieldLastMatchAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserStats {
	return predicate.UserStats(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserStats {
	return predicate.UserStats(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserStats {
	return predicate.UserStats(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserStats) predicate.UserStats {
	return predicate.UserStats(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserStats) predicate.UserStats {
	return predicate.UserStats(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserStats) predicate.UserStats {
	return predicate.UserStats(sql.NotPredicates(p))
}
