// Code generated by ent, DO NOT EDIT.

package matchparticipant

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the matchparticipant type in the database.
	Label = "match_participant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMatchID holds the string denoting the match_id field in the database.
	FieldMatchID = "match_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldJoinedAt holds the string denoting the joined_at field in the database.
	FieldJoinedAt = "joined_at"
	// FieldPaymentStatus holds the string denoting the payment_status field in the database.
	FieldPaymentStatus = "payment_status"
	// FieldPaymentMethod holds the string denoting the payment_method field in the database.
	FieldPaymentMethod = "payment_method"
	// FieldPaymentTransactionID holds the string denoting the payment_transaction_id field in the database.
	FieldPaymentTransactionID = "payment_transaction_id"
	// FieldAttendanceStatus holds the string denoting the attendance_status field in the database.
	FieldAttendanceStatus = "attendance_status"
	// FieldPlayerRating holds the string denoting the player_rating field in the database.
	FieldPlayerRating = "player_rating"
	// FieldMatchRating holds the string denoting the match_rating field in the database.
	FieldMatchRating = "match_rating"
	// FieldFeedback holds the string denoting the feedback field in the database.
	FieldFeedback = "feedback"
	// EdgeMatch holds the string denoting the match edge name in mutations.
	EdgeMatch = "match"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the matchparticipant in the database.
	Table = "match_participants"
	// MatchTable is the table that holds the match relation/edge.
	MatchTable = "match_participants"
	// MatchInverseTable is the table name for the Match entity.
	// It exists in this package in order to avoid circular dependency with the "match" package.
	MatchInverseTable = "matches"
	// MatchColumn is the table column denoting the match relation/edge.
	MatchColumn = "match_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "match_participants"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for matchparticipant fields.
var Columns = []string{
	FieldID,
	FieldMatchID,
	FieldUserID,
	FieldJoinedAt,
	FieldPaymentStatus,
	FieldPaymentMethod,
	FieldPaymentTransactionID,
	FieldAttendanceStatus,
	FieldPlayerRating,
	FieldMatchRating,
	FieldFeedback,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "match_participants"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"match_participants",
	"user_participations",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultJoinedAt holds the default value on creation for the "joined_at" field.
	DefaultJoinedAt func() time.Time
	// PaymentMethodValidator is a validator for the "payment_method" field. It is called by the builders before save.
	PaymentMethodValidator func(string) error
	// PaymentTransactionIDValidator is a validator for the "payment_transaction_id" field. It is called by the builders before save.
	PaymentTransactionIDValidator func(string) error
	// PlayerRatingValidator is a validator for the "player_rating" field. It is called by the builders before save.
	PlayerRatingValidator func(int) error
	// MatchRatingValidator is a validator for the "match_rating" field. It is called by the builders before save.
	MatchRatingValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PaymentStatus defines the type for the "payment_status" enum field.
type PaymentStatus string

// PaymentStatusPending is the default value of the PaymentStatus enum.
const DefaultPaymentStatus = PaymentStatusPending

// PaymentStatus values.
const (
	PaymentStatusPending  PaymentStatus = "pending"
	PaymentStatusPaid     PaymentStatus = "paid"
	PaymentStatusRefunded PaymentStatus = "refunded"
)

func (ps PaymentStatus) String() string {
	return string(ps)
}

// PaymentStatusValidator is a validator for the "payment_status" field enum values. It is called by the builders before save.
func PaymentStatusValidator(ps PaymentStatus) error {
	switch ps {
	case PaymentStatusPending, PaymentStatusPaid, PaymentStatusRefunded:
		return nil
	default:
		return fmt.Errorf("matchparticipant: invalid enum value for payment_status field: %q", ps)
	}
}

// AttendanceStatus defines the type for the "attendance_status" enum field.
type AttendanceStatus string

// AttendanceStatusConfirmed is the default value of the AttendanceStatus enum.
const DefaultAttendanceStatus = AttendanceStatusConfirmed

// AttendanceStatus values.
const (
	AttendanceStatusConfirmed AttendanceStatus = "confirmed"
	AttendanceStatusAttended  AttendanceStatus = "attended"
	AttendanceStatusNoShow    AttendanceStatus = "no_show"
	AttendanceStatusCancelled AttendanceStatus = "cancelled"
)

func (as AttendanceStatus) String() string {
	return string(as)
}

// AttendanceStatusValidator is a validator for the "attendance_status" field enum values. It is called by the builders before save.
func AttendanceStatusValidator(as AttendanceStatus) error {
	switch as {
	case AttendanceStatusConfirmed, AttendanceStatusAttended, AttendanceStatusNoShow, AttendanceStatusCancelled:
		return nil
	default:
		return fmt.Errorf("matchparticipant: invalid enum value for attendance_status field: %q", as)
	}
}

// OrderOption defines the ordering options for the MatchParticipant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMatchID orders the results by the match_id field.
func ByMatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByJoinedAt orders the results by the joined_at field.
func ByJoinedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinedAt, opts...).ToFunc()
}

// ByPaymentStatus orders the results by the payment_status field.
func ByPaymentStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentStatus, opts...).ToFunc()
}

// ByPaymentMethod orders the results by the payment_method field.
func ByPaymentMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentMethod, opts...).ToFunc()
}

// ByPaymentTransactionID orders the results by the payment_transaction_id field.
func ByPaymentTransactionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentTransactionID, opts...).ToFunc()
}

// ByAttendanceStatus orders the results by the attendance_status field.
func ByAttendanceStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttendanceStatus, opts...).ToFunc()
}

// ByPlayerRating orders the results by the player_rating field.
func ByPlayerRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayerRating, opts...).ToFunc()
}

// ByMatchRating orders the results by the match_rating field.
func ByMatchRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchRating, opts...).ToFunc()
}

// ByFeedback orders the results by the feedback field.
func ByFeedback(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeedback, opts...).ToFunc()
}

// ByMatchField orders the results by match field.
func ByMatchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMatchStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newMatchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MatchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, MatchTable, MatchColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
