// Code generated by ent, DO NOT EDIT.

package matchparticipant

import (
	"kicknroar/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLTE(FieldID, id))
}

// MatchID applies equality check predicate on the "match_id" field. It's identical to MatchIDEQ.
func MatchID(v uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldMatchID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldUserID, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldJoinedAt, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentTransactionID applies equality check predicate on the "payment_transaction_id" field. It's identical to PaymentTransactionIDEQ.
func PaymentTransactionID(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldPaymentTransactionID, v))
}

// PlayerRating applies equality check predicate on the "player_rating" field. It's identical to PlayerRatingEQ.
func PlayerRating(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldPlayerRating, v))
}

// MatchRating applies equality check predicate on the "match_rating" field. It's identical to MatchRatingEQ.
func MatchRating(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldMatchRating, v))
}

// Feedback applies equality check predicate on the "feedback" field. It's identical to FeedbackEQ.
func Feedback(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldFeedback, v))
}

// MatchIDEQ applies the EQ predicate on the "match_id" field.
func MatchIDEQ(v uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldMatchID, v))
}

// MatchIDNEQ applies the NEQ predicate on the "match_id" field.
func MatchIDNEQ(v uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldMatchID, v))
}

// MatchIDIn applies the In predicate on the "match_id" field.
func MatchIDIn(vs ...uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldMatchID, vs...))
}

// MatchIDNotIn applies the NotIn predicate on the "match_id" field.
func MatchIDNotIn(vs ...uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldMatchID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldUserID, vs...))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLTE(FieldJoinedAt, v))
}

// PaymentStatusEQ applies the EQ predicate on the "payment_status" field.
func PaymentStatusEQ(v PaymentStatus) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldPaymentStatus, v))
}

// PaymentStatusNEQ applies the NEQ predicate on the "payment_status" field.
func PaymentStatusNEQ(v PaymentStatus) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldPaymentStatus, v))
}

// PaymentStatusIn applies the In predicate on the "payment_status" field.
func PaymentStatusIn(vs ...PaymentStatus) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldPaymentStatus, vs...))
}

// PaymentStatusNotIn applies the NotIn predicate on the "payment_status" field.
func PaymentStatusNotIn(vs ...PaymentStatus) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldPaymentStatus, vs...))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodIsNil applies the IsNil predicate on the "payment_method" field.
func PaymentMethodIsNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIsNull(FieldPaymentMethod))
}

// PaymentMethodNotNil applies the NotNil predicate on the "payment_method" field.
func PaymentMethodNotNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotNull(FieldPaymentMethod))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// PaymentTransactionIDEQ applies the EQ predicate on the "payment_transaction_id" field.
func PaymentTransactionIDEQ(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDNEQ applies the NEQ predicate on the "payment_transaction_id" field.
func PaymentTransactionIDNEQ(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDIn applies the In predicate on the "payment_transaction_id" field.
func PaymentTransactionIDIn(vs ...string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldPaymentTransactionID, vs...))
}

// PaymentTransactionIDNotIn applies the NotIn predicate on the "payment_transaction_id" field.
func PaymentTransactionIDNotIn(vs ...string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldPaymentTransactionID, vs...))
}

// PaymentTransactionIDGT applies the GT predicate on the "payment_transaction_id" field.
func PaymentTransactionIDGT(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGT(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDGTE applies the GTE predicate on the "payment_transaction_id" field.
func PaymentTransactionIDGTE(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGTE(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDLT applies the LT predicate on the "payment_transaction_id" field.
func PaymentTransactionIDLT(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLT(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDLTE applies the LTE predicate on the "payment_transaction_id" field.
func PaymentTransactionIDLTE(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLTE(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDContains applies the Contains predicate on the "payment_transaction_id" field.
func PaymentTransactionIDContains(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldContains(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDHasPrefix applies the HasPrefix predicate on the "payment_transaction_id" field.
func PaymentTransactionIDHasPrefix(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldHasPrefix(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDHasSuffix applies the HasSuffix predicate on the "payment_transaction_id" field.
func PaymentTransactionIDHasSuffix(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldHasSuffix(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDIsNil applies the IsNil predicate on the "payment_transaction_id" field.
func PaymentTransactionIDIsNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIsNull(FieldPaymentTransactionID))
}

// PaymentTransactionIDNotNil applies the NotNil predicate on the "payment_transaction_id" field.
func PaymentTransactionIDNotNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotNull(FieldPaymentTransactionID))
}

// PaymentTransactionIDEqualFold applies the EqualFold predicate on the "payment_transaction_id" field.
func PaymentTransactionIDEqualFold(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEqualFold(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDContainsFold applies the ContainsFold predicate on the "payment_transaction_id" field.
func PaymentTransactionIDContainsFold(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldContainsFold(FieldPaymentTransactionID, v))
}

// AttendanceStatusEQ applies the EQ predicate on the "attendance_status" field.
func AttendanceStatusEQ(v AttendanceStatus) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldAttendanceStatus, v))
}

// AttendanceStatusNEQ applies the NEQ predicate on the "attendance_status" field.
func AttendanceStatusNEQ(v AttendanceStatus) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldAttendanceStatus, v))
}

// AttendanceStatusIn applies the In predicate on the "attendance_status" field.
func AttendanceStatusIn(vs ...AttendanceStatus) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldAttendanceStatus, vs...))
}

// AttendanceStatusNotIn applies the NotIn predicate on the "attendance_status" field.
func AttendanceStatusNotIn(vs ...AttendanceStatus) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldAttendanceStatus, vs...))
}

// PlayerRatingEQ applies the EQ predicate on the "player_rating" field.
func PlayerRatingEQ(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldPlayerRating, v))
}

// PlayerRatingNEQ applies the NEQ predicate on the "player_rating" field.
func PlayerRatingNEQ(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldPlayerRating, v))
}

// PlayerRatingIn applies the In predicate on the "player_rating" field.
func PlayerRatingIn(vs ...int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldPlayerRating, vs...))
}

// PlayerRatingNotIn applies the NotIn predicate on the "player_rating" field.
func PlayerRatingNotIn(vs ...int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldPlayerRating, vs...))
}

// PlayerRatingGT applies the GT predicate on the "player_rating" field.
func PlayerRatingGT(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGT(FieldPlayerRating, v))
}

// PlayerRatingGTE applies the GTE predicate on the "player_rating" field.
func PlayerRatingGTE(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGTE(FieldPlayerRating, v))
}

// PlayerRatingLT applies the LT predicate on the "player_rating" field.
func PlayerRatingLT(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLT(FieldPlayerRating, v))
}

// PlayerRatingLTE applies the LTE predicate on the "player_rating" field.
func PlayerRatingLTE(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLTE(FieldPlayerRating, v))
}

// PlayerRatingIsNil applies the IsNil predicate on the "player_rating" field.
func PlayerRatingIsNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIsNull(FieldPlayerRating))
}

// PlayerRatingNotNil applies the NotNil predicate on the "player_rating" field.
func PlayerRatingNotNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotNull(FieldPlayerRating))
}

// MatchRatingEQ applies the EQ predicate on the "match_rating" field.
func MatchRatingEQ(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldMatchRating, v))
}

// MatchRatingNEQ applies the NEQ predicate on the "match_rating" field.
func MatchRatingNEQ(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldMatchRating, v))
}

// MatchRatingIn applies the In predicate on the "match_rating" field.
func MatchRatingIn(vs ...int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldMatchRating, vs...))
}

// MatchRatingNotIn applies the NotIn predicate on the "match_rating" field.
func MatchRatingNotIn(vs ...int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldMatchRating, vs...))
}

// MatchRatingGT applies the GT predicate on the "match_rating" field.
func MatchRatingGT(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGT(FieldMatchRating, v))
}

// MatchRatingGTE applies the GTE predicate on the "match_rating" field.
func MatchRatingGTE(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGTE(FieldMatchRating, v))
}

// MatchRatingLT applies the LT predicate on the "match_rating" field.
func MatchRatingLT(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLT(FieldMatchRating, v))
}

// MatchRatingLTE applies the LTE predicate on the "match_rating" field.
func MatchRatingLTE(v int) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLTE(FieldMatchRating, v))
}

// MatchRatingIsNil applies the IsNil predicate on the "match_rating" field.
func MatchRatingIsNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIsNull(FieldMatchRating))
}

// MatchRatingNotNil applies the NotNil predicate on the "match_rating" field.
func MatchRatingNotNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotNull(FieldMatchRating))
}

// FeedbackEQ applies the EQ predicate on the "feedback" field.
func FeedbackEQ(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEQ(FieldFeedback, v))
}

// FeedbackNEQ applies the NEQ predicate on the "feedback" field.
func FeedbackNEQ(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNEQ(FieldFeedback, v))
}

// FeedbackIn applies the In predicate on the "feedback" field.
func FeedbackIn(vs ...string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIn(FieldFeedback, vs...))
}

// FeedbackNotIn applies the NotIn predicate on the "feedback" field.
func FeedbackNotIn(vs ...string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotIn(FieldFeedback, vs...))
}

// FeedbackGT applies the GT predicate on the "feedback" field.
func FeedbackGT(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGT(FieldFeedback, v))
}

// FeedbackGTE applies the GTE predicate on the "feedback" field.
func FeedbackGTE(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldGTE(FieldFeedback, v))
}

// FeedbackLT applies the LT predicate on the "feedback" field.
func FeedbackLT(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLT(FieldFeedback, v))
}

// FeedbackLTE applies the LTE predicate on the "feedback" field.
func FeedbackLTE(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldLTE(FieldFeedback, v))
}

// FeedbackContains applies the Contains predicate on the "feedback" field.
func FeedbackContains(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldContains(FieldFeedback, v))
}

// FeedbackHasPrefix applies the HasPrefix predicate on the "feedback" field.
func FeedbackHasPrefix(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldHasPrefix(FieldFeedback, v))
}

// FeedbackHasSuffix applies the HasSuffix predicate on the "feedback" field.
func FeedbackHasSuffix(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldHasSuffix(FieldFeedback, v))
}

// FeedbackIsNil applies the IsNil predicate on the "feedback" field.
func FeedbackIsNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldIsNull(FieldFeedback))
}

// FeedbackNotNil applies the NotNil predicate on the "feedback" field.
func FeedbackNotNil() predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldNotNull(FieldFeedback))
}

// FeedbackEqualFold applies the EqualFold predicate on the "feedback" field.
func FeedbackEqualFold(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldEqualFold(FieldFeedback, v))
}

// FeedbackContainsFold applies the ContainsFold predicate on the "feedback" field.
func FeedbackContainsFold(v string) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.FieldContainsFold(FieldFeedback, v))
}

// HasMatch applies the HasEdge predicate on the "match" edge.
func HasMatch() predicate.MatchParticipant {
	return predicate.MatchParticipant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MatchTable, MatchColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMatchWith applies the HasEdge predicate on the "match" edge with a given conditions (other predicates).
func HasMatchWith(preds ...predicate.Match) predicate.MatchParticipant {
	return predicate.MatchParticipant(func(s *sql.Selector) {
		step := newMatchStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.MatchParticipant {
	return predicate.MatchParticipant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.MatchParticipant {
	return predicate.MatchParticipant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MatchParticipant) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MatchParticipant) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MatchParticipant) predicate.MatchParticipant {
	return predicate.MatchParticipant(sql.NotPredicates(p))
}
